/**
 * Lucide 图标映射（桌面端）
 *
 * getIcon(name)：按图标名称字符串（PascalCase，如 "Film"）查找 Lucide 组件，
 * 适用于 icon_variant 等场景。
 */
import type { LucideIcon } from "lucide-react";
import {
  // 通用回退
  LayoutGrid,
  // 通用按名称映射（保留以兼容旧用法）
  Film,
  Book,
  Gamepad2,
  Smartphone,
  MapPin,
  Calendar,
  CalendarCheck,
  Gift,
  CheckSquare,
  FolderKanban,
  Briefcase,
  Wallet,
  Building2,
  Users,
  HeartPulse,
  Baby,
  Receipt,
  CreditCard,
  Phone,
  // 应用服务图标选择器候选
  MessageCircle,
  Mail,
  PhoneCall,
  UserPlus,
  ShoppingCart,
  ShoppingBag,
  Landmark,
  Banknote,
  Coins,
  Music,
  Headphones,
  Clapperboard,
  Tv,
  MonitorPlay,
  Palette,
  Brush,
  Dumbbell,
  Wrench,
  BookOpen,
  BookText,
  Cloud,
  CloudUpload,
  Bell,
  BellRing,
  Bookmark,
  Lightbulb,
  Folder,
  FolderOpen,
  Package,
  Box,
  Plane,
  Car,
  Utensils,
  Heart,
  Star,
  Lock,
  Key,
  Home,
  FileText,
  File,
  Camera,
  Image,
  Globe,
  Stethoscope,
  Calculator,
  Coffee,
} from "lucide-react";

/** 图标名称 → Lucide 组件映射表（PascalCase 名称） */
export const iconMap: Record<string, LucideIcon> = {
  Film,
  Book,
  Gamepad2,
  Smartphone,
  MapPin,
  Calendar,
  CalendarCheck,
  Gift,
  CheckSquare,
  FolderKanban,
  Briefcase,
  Wallet,
  Building2,
  Users,
  HeartPulse,
  Baby,
  Receipt,
  CreditCard,
  Phone,
  MessageCircle,
  Mail,
  PhoneCall,
  UserPlus,
  ShoppingCart,
  ShoppingBag,
  Landmark,
  Banknote,
  Coins,
  Music,
  Headphones,
  Clapperboard,
  Tv,
  MonitorPlay,
  Palette,
  Brush,
  Dumbbell,
  Wrench,
  BookOpen,
  BookText,
  Cloud,
  CloudUpload,
  Bell,
  BellRing,
  Bookmark,
  Lightbulb,
  Folder,
  FolderOpen,
  Package,
  Box,
  Plane,
  Car,
  Utensils,
  Heart,
  Star,
  Lock,
  Key,
  Home,
  FileText,
  File,
  Camera,
  Image,
  Globe,
  Stethoscope,
  Calculator,
  Coffee,
};

/**
 * 按 PascalCase 名称获取 Lucide 图标组件
 * 未知名称回退到 LayoutGrid，保证渲染不中断
 */
export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? LayoutGrid;
}

/**
 * 应用服务图标选择器候选（展示顺序即此顺序；名称与 iconMap 完全一致）
 */
export const ICON_PICKER_CHOICES: string[] = [
  "MessageCircle", "Mail", "Phone", "PhoneCall", "Users", "UserPlus",
  "Wallet", "CreditCard", "ShoppingCart", "ShoppingBag", "Banknote", "Landmark", "Coins",
  "Gamepad2", "Music", "Headphones", "Film", "Clapperboard", "Tv", "MonitorPlay",
  "Palette", "Brush", "Dumbbell", "Wrench", "BookOpen", "BookText",
  "Cloud", "CloudUpload", "Bell", "BellRing", "Bookmark", "Lightbulb",
  "Folder", "FolderOpen", "Package", "Box", "Plane", "Car", "Utensils",
  "Heart", "Star", "Lock", "Key", "Home", "FileText", "File",
  "Camera", "Image", "Globe", "Gift", "Stethoscope", "Building2", "Briefcase",
  "Calculator", "Smartphone", "Calendar", "MapPin", "Coffee",
];
