// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/asset.dart';
import 'api/auth.dart';
import 'api/csv_import.dart';
import 'api/dto.dart';
import 'api/events.dart';
import 'api/holiday.dart';
import 'api/plaintext_export.dart';
import 'api/saved_filter.dart';
import 'api/search.dart';
import 'api/state.dart';
import 'api/stats.dart';
import 'api/sync.dart';
import 'api/todo.dart';
import 'api/trash.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DbEventDto> dco_decode_StreamSink_db_event_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ReminderDueDto> dco_decode_StreamSink_reminder_due_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ListFilter dco_decode_box_autoadd_list_filter(dynamic raw);

  @protected
  SyncConfigInput dco_decode_box_autoadd_sync_config_input(dynamic raw);

  @protected
  SyncConfigView dco_decode_box_autoadd_sync_config_view(dynamic raw);

  @protected
  TodoCommentCreateInput dco_decode_box_autoadd_todo_comment_create_input(
    dynamic raw,
  );

  @protected
  TodoLabelCreateInput dco_decode_box_autoadd_todo_label_create_input(
    dynamic raw,
  );

  @protected
  TodoProjectCreateInput dco_decode_box_autoadd_todo_project_create_input(
    dynamic raw,
  );

  @protected
  TodoReminderCreateInput dco_decode_box_autoadd_todo_reminder_create_input(
    dynamic raw,
  );

  @protected
  TodoSavedFilterCreateInput
  dco_decode_box_autoadd_todo_saved_filter_create_input(dynamic raw);

  @protected
  TodoSavedFilterUpdateInput
  dco_decode_box_autoadd_todo_saved_filter_update_input(dynamic raw);

  @protected
  TodoSubtaskCreateInput dco_decode_box_autoadd_todo_subtask_create_input(
    dynamic raw,
  );

  @protected
  TodoTask dco_decode_box_autoadd_todo_task(dynamic raw);

  @protected
  TodoTaskCreateInput dco_decode_box_autoadd_todo_task_create_input(
    dynamic raw,
  );

  @protected
  TodoTaskLabelCreateInput dco_decode_box_autoadd_todo_task_label_create_input(
    dynamic raw,
  );

  @protected
  TodoTaskRelationCreateInput
  dco_decode_box_autoadd_todo_task_relation_create_input(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  CommentSearchHit dco_decode_comment_search_hit(dynamic raw);

  @protected
  CompleteTaskResult dco_decode_complete_task_result(dynamic raw);

  @protected
  CsvImportPreviewView dco_decode_csv_import_preview_view(dynamic raw);

  @protected
  CsvImportRowView dco_decode_csv_import_row_view(dynamic raw);

  @protected
  CsvImportStatsView dco_decode_csv_import_stats_view(dynamic raw);

  @protected
  DbEventDto dco_decode_db_event_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GlobalSearchResult dco_decode_global_search_result(dynamic raw);

  @protected
  HolidayInfo dco_decode_holiday_info(dynamic raw);

  @protected
  HolidayMeta dco_decode_holiday_meta(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CommentSearchHit> dco_decode_list_comment_search_hit(dynamic raw);

  @protected
  List<CsvImportRowView> dco_decode_list_csv_import_row_view(dynamic raw);

  @protected
  ListFilter dco_decode_list_filter(dynamic raw);

  @protected
  List<HolidayInfo> dco_decode_list_holiday_info(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StatsHeatmapCell> dco_decode_list_stats_heatmap_cell(dynamic raw);

  @protected
  List<StatsPriorityRow> dco_decode_list_stats_priority_row(dynamic raw);

  @protected
  List<StatsProjectRow> dco_decode_list_stats_project_row(dynamic raw);

  @protected
  List<StatsWeekdayRow> dco_decode_list_stats_weekday_row(dynamic raw);

  @protected
  List<TableCount> dco_decode_list_table_count(dynamic raw);

  @protected
  List<TaskAttachmentView> dco_decode_list_task_attachment_view(dynamic raw);

  @protected
  List<TaskLabelWithId> dco_decode_list_task_label_with_id(dynamic raw);

  @protected
  List<TodoComment> dco_decode_list_todo_comment(dynamic raw);

  @protected
  List<TodoLabel> dco_decode_list_todo_label(dynamic raw);

  @protected
  List<TodoProject> dco_decode_list_todo_project(dynamic raw);

  @protected
  List<TodoReminder> dco_decode_list_todo_reminder(dynamic raw);

  @protected
  List<TodoSavedFilter> dco_decode_list_todo_saved_filter(dynamic raw);

  @protected
  List<TodoSubtask> dco_decode_list_todo_subtask(dynamic raw);

  @protected
  List<TodoTask> dco_decode_list_todo_task(dynamic raw);

  @protected
  List<TodoTaskLabel> dco_decode_list_todo_task_label(dynamic raw);

  @protected
  List<TodoTaskRelation> dco_decode_list_todo_task_relation(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SyncConfigView? dco_decode_opt_box_autoadd_sync_config_view(dynamic raw);

  @protected
  TodoTask? dco_decode_opt_box_autoadd_todo_task(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  PlaintextExportView dco_decode_plaintext_export_view(dynamic raw);

  @protected
  ReminderDueDto dco_decode_reminder_due_dto(dynamic raw);

  @protected
  StatsAggregate dco_decode_stats_aggregate(dynamic raw);

  @protected
  StatsHeatmap dco_decode_stats_heatmap(dynamic raw);

  @protected
  StatsHeatmapCell dco_decode_stats_heatmap_cell(dynamic raw);

  @protected
  StatsOverview dco_decode_stats_overview(dynamic raw);

  @protected
  StatsPriorityRow dco_decode_stats_priority_row(dynamic raw);

  @protected
  StatsProjectRow dco_decode_stats_project_row(dynamic raw);

  @protected
  StatsStreak dco_decode_stats_streak(dynamic raw);

  @protected
  StatsWeekdayRow dco_decode_stats_weekday_row(dynamic raw);

  @protected
  SyncConfigInput dco_decode_sync_config_input(dynamic raw);

  @protected
  SyncConfigView dco_decode_sync_config_view(dynamic raw);

  @protected
  SyncCryptoStatus dco_decode_sync_crypto_status(dynamic raw);

  @protected
  TableCount dco_decode_table_count(dynamic raw);

  @protected
  TaskAttachmentView dco_decode_task_attachment_view(dynamic raw);

  @protected
  TaskLabelWithId dco_decode_task_label_with_id(dynamic raw);

  @protected
  TodoComment dco_decode_todo_comment(dynamic raw);

  @protected
  TodoCommentCreateInput dco_decode_todo_comment_create_input(dynamic raw);

  @protected
  TodoLabel dco_decode_todo_label(dynamic raw);

  @protected
  TodoLabelCreateInput dco_decode_todo_label_create_input(dynamic raw);

  @protected
  TodoProject dco_decode_todo_project(dynamic raw);

  @protected
  TodoProjectCreateInput dco_decode_todo_project_create_input(dynamic raw);

  @protected
  TodoReminder dco_decode_todo_reminder(dynamic raw);

  @protected
  TodoReminderCreateInput dco_decode_todo_reminder_create_input(dynamic raw);

  @protected
  TodoSavedFilter dco_decode_todo_saved_filter(dynamic raw);

  @protected
  TodoSavedFilterCreateInput dco_decode_todo_saved_filter_create_input(
    dynamic raw,
  );

  @protected
  TodoSavedFilterUpdateInput dco_decode_todo_saved_filter_update_input(
    dynamic raw,
  );

  @protected
  TodoSubtask dco_decode_todo_subtask(dynamic raw);

  @protected
  TodoSubtaskCreateInput dco_decode_todo_subtask_create_input(dynamic raw);

  @protected
  TodoTask dco_decode_todo_task(dynamic raw);

  @protected
  TodoTaskCreateInput dco_decode_todo_task_create_input(dynamic raw);

  @protected
  TodoTaskDetail dco_decode_todo_task_detail(dynamic raw);

  @protected
  TodoTaskLabel dco_decode_todo_task_label(dynamic raw);

  @protected
  TodoTaskLabelCreateInput dco_decode_todo_task_label_create_input(dynamic raw);

  @protected
  TodoTaskRelation dco_decode_todo_task_relation(dynamic raw);

  @protected
  TodoTaskRelationCreateInput dco_decode_todo_task_relation_create_input(
    dynamic raw,
  );

  @protected
  TrashMeta dco_decode_trash_meta(dynamic raw);

  @protected
  TrashPurgeStats dco_decode_trash_purge_stats(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DbEventDto> sse_decode_StreamSink_db_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ReminderDueDto> sse_decode_StreamSink_reminder_due_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ListFilter sse_decode_box_autoadd_list_filter(SseDeserializer deserializer);

  @protected
  SyncConfigInput sse_decode_box_autoadd_sync_config_input(
    SseDeserializer deserializer,
  );

  @protected
  SyncConfigView sse_decode_box_autoadd_sync_config_view(
    SseDeserializer deserializer,
  );

  @protected
  TodoCommentCreateInput sse_decode_box_autoadd_todo_comment_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoLabelCreateInput sse_decode_box_autoadd_todo_label_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoProjectCreateInput sse_decode_box_autoadd_todo_project_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoReminderCreateInput sse_decode_box_autoadd_todo_reminder_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoSavedFilterCreateInput
  sse_decode_box_autoadd_todo_saved_filter_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoSavedFilterUpdateInput
  sse_decode_box_autoadd_todo_saved_filter_update_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoSubtaskCreateInput sse_decode_box_autoadd_todo_subtask_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoTask sse_decode_box_autoadd_todo_task(SseDeserializer deserializer);

  @protected
  TodoTaskCreateInput sse_decode_box_autoadd_todo_task_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoTaskLabelCreateInput sse_decode_box_autoadd_todo_task_label_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoTaskRelationCreateInput
  sse_decode_box_autoadd_todo_task_relation_create_input(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  CommentSearchHit sse_decode_comment_search_hit(SseDeserializer deserializer);

  @protected
  CompleteTaskResult sse_decode_complete_task_result(
    SseDeserializer deserializer,
  );

  @protected
  CsvImportPreviewView sse_decode_csv_import_preview_view(
    SseDeserializer deserializer,
  );

  @protected
  CsvImportRowView sse_decode_csv_import_row_view(SseDeserializer deserializer);

  @protected
  CsvImportStatsView sse_decode_csv_import_stats_view(
    SseDeserializer deserializer,
  );

  @protected
  DbEventDto sse_decode_db_event_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GlobalSearchResult sse_decode_global_search_result(
    SseDeserializer deserializer,
  );

  @protected
  HolidayInfo sse_decode_holiday_info(SseDeserializer deserializer);

  @protected
  HolidayMeta sse_decode_holiday_meta(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CommentSearchHit> sse_decode_list_comment_search_hit(
    SseDeserializer deserializer,
  );

  @protected
  List<CsvImportRowView> sse_decode_list_csv_import_row_view(
    SseDeserializer deserializer,
  );

  @protected
  ListFilter sse_decode_list_filter(SseDeserializer deserializer);

  @protected
  List<HolidayInfo> sse_decode_list_holiday_info(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StatsHeatmapCell> sse_decode_list_stats_heatmap_cell(
    SseDeserializer deserializer,
  );

  @protected
  List<StatsPriorityRow> sse_decode_list_stats_priority_row(
    SseDeserializer deserializer,
  );

  @protected
  List<StatsProjectRow> sse_decode_list_stats_project_row(
    SseDeserializer deserializer,
  );

  @protected
  List<StatsWeekdayRow> sse_decode_list_stats_weekday_row(
    SseDeserializer deserializer,
  );

  @protected
  List<TableCount> sse_decode_list_table_count(SseDeserializer deserializer);

  @protected
  List<TaskAttachmentView> sse_decode_list_task_attachment_view(
    SseDeserializer deserializer,
  );

  @protected
  List<TaskLabelWithId> sse_decode_list_task_label_with_id(
    SseDeserializer deserializer,
  );

  @protected
  List<TodoComment> sse_decode_list_todo_comment(SseDeserializer deserializer);

  @protected
  List<TodoLabel> sse_decode_list_todo_label(SseDeserializer deserializer);

  @protected
  List<TodoProject> sse_decode_list_todo_project(SseDeserializer deserializer);

  @protected
  List<TodoReminder> sse_decode_list_todo_reminder(
    SseDeserializer deserializer,
  );

  @protected
  List<TodoSavedFilter> sse_decode_list_todo_saved_filter(
    SseDeserializer deserializer,
  );

  @protected
  List<TodoSubtask> sse_decode_list_todo_subtask(SseDeserializer deserializer);

  @protected
  List<TodoTask> sse_decode_list_todo_task(SseDeserializer deserializer);

  @protected
  List<TodoTaskLabel> sse_decode_list_todo_task_label(
    SseDeserializer deserializer,
  );

  @protected
  List<TodoTaskRelation> sse_decode_list_todo_task_relation(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SyncConfigView? sse_decode_opt_box_autoadd_sync_config_view(
    SseDeserializer deserializer,
  );

  @protected
  TodoTask? sse_decode_opt_box_autoadd_todo_task(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  PlaintextExportView sse_decode_plaintext_export_view(
    SseDeserializer deserializer,
  );

  @protected
  ReminderDueDto sse_decode_reminder_due_dto(SseDeserializer deserializer);

  @protected
  StatsAggregate sse_decode_stats_aggregate(SseDeserializer deserializer);

  @protected
  StatsHeatmap sse_decode_stats_heatmap(SseDeserializer deserializer);

  @protected
  StatsHeatmapCell sse_decode_stats_heatmap_cell(SseDeserializer deserializer);

  @protected
  StatsOverview sse_decode_stats_overview(SseDeserializer deserializer);

  @protected
  StatsPriorityRow sse_decode_stats_priority_row(SseDeserializer deserializer);

  @protected
  StatsProjectRow sse_decode_stats_project_row(SseDeserializer deserializer);

  @protected
  StatsStreak sse_decode_stats_streak(SseDeserializer deserializer);

  @protected
  StatsWeekdayRow sse_decode_stats_weekday_row(SseDeserializer deserializer);

  @protected
  SyncConfigInput sse_decode_sync_config_input(SseDeserializer deserializer);

  @protected
  SyncConfigView sse_decode_sync_config_view(SseDeserializer deserializer);

  @protected
  SyncCryptoStatus sse_decode_sync_crypto_status(SseDeserializer deserializer);

  @protected
  TableCount sse_decode_table_count(SseDeserializer deserializer);

  @protected
  TaskAttachmentView sse_decode_task_attachment_view(
    SseDeserializer deserializer,
  );

  @protected
  TaskLabelWithId sse_decode_task_label_with_id(SseDeserializer deserializer);

  @protected
  TodoComment sse_decode_todo_comment(SseDeserializer deserializer);

  @protected
  TodoCommentCreateInput sse_decode_todo_comment_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoLabel sse_decode_todo_label(SseDeserializer deserializer);

  @protected
  TodoLabelCreateInput sse_decode_todo_label_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoProject sse_decode_todo_project(SseDeserializer deserializer);

  @protected
  TodoProjectCreateInput sse_decode_todo_project_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoReminder sse_decode_todo_reminder(SseDeserializer deserializer);

  @protected
  TodoReminderCreateInput sse_decode_todo_reminder_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoSavedFilter sse_decode_todo_saved_filter(SseDeserializer deserializer);

  @protected
  TodoSavedFilterCreateInput sse_decode_todo_saved_filter_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoSavedFilterUpdateInput sse_decode_todo_saved_filter_update_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoSubtask sse_decode_todo_subtask(SseDeserializer deserializer);

  @protected
  TodoSubtaskCreateInput sse_decode_todo_subtask_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoTask sse_decode_todo_task(SseDeserializer deserializer);

  @protected
  TodoTaskCreateInput sse_decode_todo_task_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoTaskDetail sse_decode_todo_task_detail(SseDeserializer deserializer);

  @protected
  TodoTaskLabel sse_decode_todo_task_label(SseDeserializer deserializer);

  @protected
  TodoTaskLabelCreateInput sse_decode_todo_task_label_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TodoTaskRelation sse_decode_todo_task_relation(SseDeserializer deserializer);

  @protected
  TodoTaskRelationCreateInput sse_decode_todo_task_relation_create_input(
    SseDeserializer deserializer,
  );

  @protected
  TrashMeta sse_decode_trash_meta(SseDeserializer deserializer);

  @protected
  TrashPurgeStats sse_decode_trash_purge_stats(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_db_event_dto_Sse(
    RustStreamSink<DbEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_reminder_due_dto_Sse(
    RustStreamSink<ReminderDueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_filter(
    ListFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_config_input(
    SyncConfigInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_config_view(
    SyncConfigView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_comment_create_input(
    TodoCommentCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_label_create_input(
    TodoLabelCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_project_create_input(
    TodoProjectCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_reminder_create_input(
    TodoReminderCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_saved_filter_create_input(
    TodoSavedFilterCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_saved_filter_update_input(
    TodoSavedFilterUpdateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_subtask_create_input(
    TodoSubtaskCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_task(
    TodoTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_task_create_input(
    TodoTaskCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_task_label_create_input(
    TodoTaskLabelCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_todo_task_relation_create_input(
    TodoTaskRelationCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_comment_search_hit(
    CommentSearchHit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_complete_task_result(
    CompleteTaskResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_csv_import_preview_view(
    CsvImportPreviewView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_csv_import_row_view(
    CsvImportRowView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_csv_import_stats_view(
    CsvImportStatsView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_event_dto(DbEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_global_search_result(
    GlobalSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_holiday_info(HolidayInfo self, SseSerializer serializer);

  @protected
  void sse_encode_holiday_meta(HolidayMeta self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comment_search_hit(
    List<CommentSearchHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_csv_import_row_view(
    List<CsvImportRowView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_filter(ListFilter self, SseSerializer serializer);

  @protected
  void sse_encode_list_holiday_info(
    List<HolidayInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stats_heatmap_cell(
    List<StatsHeatmapCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stats_priority_row(
    List<StatsPriorityRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stats_project_row(
    List<StatsProjectRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stats_weekday_row(
    List<StatsWeekdayRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_count(
    List<TableCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_attachment_view(
    List<TaskAttachmentView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_label_with_id(
    List<TaskLabelWithId> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_comment(
    List<TodoComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_label(
    List<TodoLabel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_project(
    List<TodoProject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_reminder(
    List<TodoReminder> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_saved_filter(
    List<TodoSavedFilter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_subtask(
    List<TodoSubtask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_task(List<TodoTask> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_task_label(
    List<TodoTaskLabel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_todo_task_relation(
    List<TodoTaskRelation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_config_view(
    SyncConfigView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_todo_task(
    TodoTask? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_plaintext_export_view(
    PlaintextExportView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reminder_due_dto(
    ReminderDueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stats_aggregate(
    StatsAggregate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stats_heatmap(StatsHeatmap self, SseSerializer serializer);

  @protected
  void sse_encode_stats_heatmap_cell(
    StatsHeatmapCell self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stats_overview(StatsOverview self, SseSerializer serializer);

  @protected
  void sse_encode_stats_priority_row(
    StatsPriorityRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stats_project_row(
    StatsProjectRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stats_streak(StatsStreak self, SseSerializer serializer);

  @protected
  void sse_encode_stats_weekday_row(
    StatsWeekdayRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_config_input(
    SyncConfigInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_config_view(
    SyncConfigView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_crypto_status(
    SyncCryptoStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_table_count(TableCount self, SseSerializer serializer);

  @protected
  void sse_encode_task_attachment_view(
    TaskAttachmentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_task_label_with_id(
    TaskLabelWithId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_comment(TodoComment self, SseSerializer serializer);

  @protected
  void sse_encode_todo_comment_create_input(
    TodoCommentCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_label(TodoLabel self, SseSerializer serializer);

  @protected
  void sse_encode_todo_label_create_input(
    TodoLabelCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_project(TodoProject self, SseSerializer serializer);

  @protected
  void sse_encode_todo_project_create_input(
    TodoProjectCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_reminder(TodoReminder self, SseSerializer serializer);

  @protected
  void sse_encode_todo_reminder_create_input(
    TodoReminderCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_saved_filter(
    TodoSavedFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_saved_filter_create_input(
    TodoSavedFilterCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_saved_filter_update_input(
    TodoSavedFilterUpdateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_subtask(TodoSubtask self, SseSerializer serializer);

  @protected
  void sse_encode_todo_subtask_create_input(
    TodoSubtaskCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_task(TodoTask self, SseSerializer serializer);

  @protected
  void sse_encode_todo_task_create_input(
    TodoTaskCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_task_detail(
    TodoTaskDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_task_label(TodoTaskLabel self, SseSerializer serializer);

  @protected
  void sse_encode_todo_task_label_create_input(
    TodoTaskLabelCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_task_relation(
    TodoTaskRelation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_todo_task_relation_create_input(
    TodoTaskRelationCreateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trash_meta(TrashMeta self, SseSerializer serializer);

  @protected
  void sse_encode_trash_purge_stats(
    TrashPurgeStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
