// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 查询单任务活动历史（倒序；limit 缺省 30、上限 100 在 core 收口）
Future<List<ActivityLogRow>> taskActivityList({
  required PlatformInt64 taskId,
  PlatformInt64? limit,
}) => RustLib.instance.api.crateApiActivityLogTaskActivityList(
  taskId: taskId,
  limit: limit,
);
