// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 上传并挂载附件到任务（bytes 由 Dart file_picker 读得）
Future<TaskAttachmentView> taskAttachmentAdd({
  required PlatformInt64 taskId,
  required String fileName,
  required String mimeType,
  required List<int> data,
}) => RustLib.instance.api.crateApiAssetTaskAttachmentAdd(
  taskId: taskId,
  fileName: fileName,
  mimeType: mimeType,
  data: data,
);

/// 列出任务全部附件（含本地缓存状态）
Future<List<TaskAttachmentView>> taskAttachmentsList({
  required PlatformInt64 taskId,
}) => RustLib.instance.api.crateApiAssetTaskAttachmentsList(taskId: taskId);

/// 读取附件本地文件字节（详情页预览/保存用）
Future<Uint8List> taskAttachmentRead({required String hash}) =>
    RustLib.instance.api.crateApiAssetTaskAttachmentRead(hash: hash);

/// 卸下任务附件（软删关联；孤儿二进制的本地清理由 GC 负责）
Future<void> taskAttachmentRemove({required PlatformInt64 linkId}) =>
    RustLib.instance.api.crateApiAssetTaskAttachmentRemove(linkId: linkId);

/// 本地附件 GC（清无引用文件与账本行），返回清理数
Future<BigInt> attachmentsGc() =>
    RustLib.instance.api.crateApiAssetAttachmentsGc();
