// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dir_of`

/// 桥接探活（对应桌面 ping；验证 Dart → Rust → orbit_core 通路）
Future<String> ping() => RustLib.instance.api.crateApiAuthPing();

/// SHA-256 哈希（对应桌面 crypto_sha256；前端透传 hex 字符串）
Future<String> cryptoSha256({required String input}) =>
    RustLib.instance.api.crateApiAuthCryptoSha256(input: input);

/// 生成密码学安全随机字节并以 hex 返回（对应桌面 crypto_random_hex）
Future<String> cryptoRandomHex({required int len}) =>
    RustLib.instance.api.crateApiAuthCryptoRandomHex(len: len);

/// 初始化明文数据库（未设置主密码时使用）
///
/// 成功后全局状态就绪（事件转发由 Dart 先行调用 subscribe_db_changes 建立）。
Future<void> dbInitPlaintext({required String baseDir}) =>
    RustLib.instance.api.crateApiAuthDbInitPlaintext(baseDir: baseDir);

/// 初始化加密数据库（已解锁主密码后使用）
///
/// hex 格式 key 转换为 SQLCipher 的 `x'...'` 格式（与桌面一致）。
Future<void> dbInitEncrypted({
  required String baseDir,
  required String dbKeyHex,
}) => RustLib.instance.api.crateApiAuthDbInitEncrypted(
  baseDir: baseDir,
  dbKeyHex: dbKeyHex,
);

/// 查询数据库是否已初始化
Future<bool> dbIsReady() => RustLib.instance.api.crateApiAuthDbIsReady();

/// 写入当前设备 ID（进程级 OnceCell，DB 初始化后调用一次）
Future<void> dbSetDeviceId({required String deviceId}) =>
    RustLib.instance.api.crateApiAuthDbSetDeviceId(deviceId: deviceId);

/// 读取当前设备 ID（未设置时返回空字符串）
Future<String> dbGetDeviceId() =>
    RustLib.instance.api.crateApiAuthDbGetDeviceId();

/// 移除状态（迁移场景：pool 已 close 后由 Dart 调用，随后重开连接池）
Future<void> dbResetState() => RustLib.instance.api.crateApiAuthDbResetState();

/// 是否已设置主密码（启动门控第一步）
Future<bool> masterAuthHas({required String baseDir}) =>
    RustLib.instance.api.crateApiAuthMasterAuthHas(baseDir: baseDir);

/// 初始化主密码（首次设置），返回 db_key_hex
///
/// 典型流程：master_auth_init(pw) → db_init_encrypted(base_dir, dbKeyHex)
Future<String> masterAuthInit({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiAuthMasterAuthInit(
  baseDir: baseDir,
  password: password,
);

/// 解锁主密码，返回 db_key_hex；密码错误抛异常
Future<String> masterAuthUnlock({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiAuthMasterAuthUnlock(
  baseDir: baseDir,
  password: password,
);

/// 仅验证主密码是否正确（敏感操作前二次确认）
Future<bool> masterAuthVerify({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiAuthMasterAuthVerify(
  baseDir: baseDir,
  password: password,
);

/// 修改主密码（校验旧密码后重写 master_auth.json；数据库 Key 不变）
///
/// 对齐桌面 `master_auth_change_password`。注意：本函数只换「开屏密码包装」，
/// 数据库文件的加密 Key 不受影响，故无需重开连接池。
Future<void> masterAuthChangePassword({
  required String baseDir,
  required String oldPassword,
  required String newPassword,
}) => RustLib.instance.api.crateApiAuthMasterAuthChangePassword(
  baseDir: baseDir,
  oldPassword: oldPassword,
  newPassword: newPassword,
);

/// 清除主密码（删除 master_auth.json，此后以明文模式打开）
///
/// 对齐桌面 `master_auth_clear`。**调用前必须已完成
/// [db_migrate_to_plaintext]**，否则加密数据库将无法打开。
Future<void> masterAuthClear({required String baseDir}) =>
    RustLib.instance.api.crateApiAuthMasterAuthClear(baseDir: baseDir);

/// 加密库 → 明文库迁移（设置页「关闭加密」场景）
///
/// 流程与桌面一致：WAL checkpoint → ATTACH 明文临时库 → sqlcipher_export →
/// 关闭旧连接池 → 用明文文件替换 → 清空全局状态。
/// **调用方（Dart）在返回后须重新走 db_init_plaintext 才可继续操作**，
/// 否则后续命令报 `[not_initialized]`。
Future<void> dbMigrateToPlaintext() =>
    RustLib.instance.api.crateApiAuthDbMigrateToPlaintext();

/// 明文库 → 加密库迁移（首次设置主密码场景）
///
/// 流程与桌面一致：sqlcipher_export 到加密临时文件 → 关闭旧连接池 →
/// 文件替换 → 清空全局状态。**调用方须先 master_auth_init 持久化 meta，
/// 返回后再 db_init_encrypted(db_key_hex) 重开**。
Future<void> dbMigrateToEncrypted({required String dbKeyHex}) =>
    RustLib.instance.api.crateApiAuthDbMigrateToEncrypted(dbKeyHex: dbKeyHex);
