// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dir_of`

/// 初始化明文数据库（未设置主密码时使用）
///
/// 成功后全局状态就绪（事件转发由 Dart 先行调用 subscribe_db_changes 建立）。
Future<void> dbInitPlaintext({required String baseDir}) =>
    RustLib.instance.api.crateApiAuthDbInitPlaintext(baseDir: baseDir);

/// 初始化加密数据库（已解锁主密码后使用）
///
/// hex 格式 key 转换为 SQLCipher 的 `x'...'` 格式（与桌面一致）。
Future<void> dbInitEncrypted({
  required String baseDir,
  required String dbKeyHex,
}) => RustLib.instance.api.crateApiAuthDbInitEncrypted(
  baseDir: baseDir,
  dbKeyHex: dbKeyHex,
);

/// 查询数据库是否已初始化
Future<bool> dbIsReady() => RustLib.instance.api.crateApiAuthDbIsReady();

/// 写入当前设备 ID（进程级 OnceCell，DB 初始化后调用一次）
Future<void> dbSetDeviceId({required String deviceId}) =>
    RustLib.instance.api.crateApiAuthDbSetDeviceId(deviceId: deviceId);

/// 读取当前设备 ID（未设置时返回空字符串）
Future<String> dbGetDeviceId() =>
    RustLib.instance.api.crateApiAuthDbGetDeviceId();

/// 移除状态（迁移场景：pool 已 close 后由 Dart 调用，随后重开连接池）
Future<void> dbResetState() => RustLib.instance.api.crateApiAuthDbResetState();

/// 是否已设置主密码（启动门控第一步）
Future<bool> masterAuthHas({required String baseDir}) =>
    RustLib.instance.api.crateApiAuthMasterAuthHas(baseDir: baseDir);

/// 初始化主密码（首次设置），返回 db_key_hex
///
/// 典型流程：master_auth_init(pw) → db_init_encrypted(base_dir, dbKeyHex)
Future<String> masterAuthInit({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiAuthMasterAuthInit(
  baseDir: baseDir,
  password: password,
);

/// 解锁主密码，返回 db_key_hex；密码错误抛异常
Future<String> masterAuthUnlock({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiAuthMasterAuthUnlock(
  baseDir: baseDir,
  password: password,
);

/// 仅验证主密码是否正确（敏感操作前二次确认）
Future<bool> masterAuthVerify({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiAuthMasterAuthVerify(
  baseDir: baseDir,
  password: password,
);
