// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_decode`

/// 生成 biometric 密钥链三件套（Base64 standard 编码，供 Dart 写入 Secure Storage）
///
/// 调用前提：用户已通过主密码解锁（本次会话持有 DB Key），且刚通过
/// local_auth 认证成功。返回值即 Secure Storage 的存储载荷：
/// - `encrypted_db_key_bio`：AES-256-GCM(Biometric Key, DB Key, nonce)
/// - `biometric_key`：32 字节随机 Biometric Key
/// - `nonce`：12 字节随机 nonce
///
/// 随机性由 core::crypto::random 提供（ring OsRng）。
Future<BiometricSecretBundle> biometricSetup({required String dbKeyHex}) =>
    RustLib.instance.api.crateApiBiometricBiometricSetup(dbKeyHex: dbKeyHex);

/// 用 Biometric Key 解密出 DB Key hex（对齐 masterAuthUnlock 契约，
/// 不直接初始化数据库）
///
/// Dart 侧流程：local_auth 认证通过 → Secure Storage 读三件套 → 调本函数
/// 拿 db_key_hex → dbInitEncrypted —— 与密码解锁路径在 BootGate 汇合为
/// 同一终态，保持 DB 初始化单一路径。密钥错误（GCM tag 校验失败）抛
/// `[biometric_failed]`，由 UnlockPage 展示后回落密码输入。
Future<String> biometricUnlock({
  required String encryptedDbKeyBioBase64,
  required String biometricKeyBase64,
  required String nonceBase64,
}) => RustLib.instance.api.crateApiBiometricBiometricUnlock(
  encryptedDbKeyBioBase64: encryptedDbKeyBioBase64,
  biometricKeyBase64: biometricKeyBase64,
  nonceBase64: nonceBase64,
);

/// 关闭生物识别前的密码确认（防误触；Dart 侧验证通过后删除 Secure Storage 三件套）
///
/// 仅验证主密码是否正确，不产生任何写入；真正的密钥链清除在 Dart 侧
/// 删除 Secure Storage 三键后即完成，Rust 无状态可清。
Future<void> biometricDisable({
  required String baseDir,
  required String password,
}) => RustLib.instance.api.crateApiBiometricBiometricDisable(
  baseDir: baseDir,
  password: password,
);

/// biometric 密钥链三件套（Base64 standard 编码）
class BiometricSecretBundle {
  final String encryptedDbKeyBio;
  final String biometricKey;
  final String nonce;

  const BiometricSecretBundle({
    required this.encryptedDbKeyBio,
    required this.biometricKey,
    required this.nonce,
  });

  @override
  int get hashCode =>
      encryptedDbKeyBio.hashCode ^ biometricKey.hashCode ^ nonce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiometricSecretBundle &&
          runtimeType == other.runtimeType &&
          encryptedDbKeyBio == other.encryptedDbKeyBio &&
          biometricKey == other.biometricKey &&
          nonce == other.nonce;
}
