// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`

/// 预览导入（不写库）：解析 + 映射 + 统计（对应桌面 csv_import_preview）
Future<CsvImportPreviewView> csvImportPreview({
  required String content,
  required String preset,
  BigInt? previewLimit,
}) => RustLib.instance.api.crateApiCsvImportCsvImportPreview(
  content: content,
  preset: preset,
  previewLimit: previewLimit,
);

/// 执行导入（写库）：项目自动创建、逐行独立成败（对应桌面 csv_import_execute）
Future<CsvImportStatsView> csvImportExecute({
  required String content,
  required String preset,
}) => RustLib.instance.api.crateApiCsvImportCsvImportExecute(
  content: content,
  preset: preset,
);
