// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// 读摘要偏好（对应桌面 digest_prefs）
Future<DigestPrefs> digestPrefs() =>
    RustLib.instance.api.crateApiDigestDigestPrefs();

/// 设置摘要偏好（hour 0–23 / minute 0–59；对应桌面 digest_set_prefs）
Future<void> digestSetPrefs({
  required bool enabled,
  required PlatformInt64 hour,
  required PlatformInt64 minute,
}) => RustLib.instance.api.crateApiDigestDigestSetPrefs(
  enabled: enabled,
  hour: hour,
  minute: minute,
);

/// 当前时刻摘要计数（设置页预览；对应桌面 digest_summary）
Future<DigestSummary> digestSummary() =>
    RustLib.instance.api.crateApiDigestDigestSummary();

/// 摘要通知文案（core `summary_body` 过桥；Dart 排程时取一次作为通知正文）
///
/// 排程时快照：系统闹钟的正文在排程那一刻固化，应用被杀后无法再算。
/// 因此正文携带的是「排程时刻」的计数，重排（启动/db 变更）时刷新。
Future<String> digestBody() => RustLib.instance.api.crateApiDigestDigestBody();

/// 摘要偏好（镜像 core digest_api::DigestPrefs）
class DigestPrefs {
  /// 总开关（默认 false：打扰型功能需显式开启）
  final bool enabled;

  /// 目标小时（0–23）
  final PlatformInt64 hour;

  /// 目标分钟（0–59）
  final PlatformInt64 minute;

  const DigestPrefs({
    required this.enabled,
    required this.hour,
    required this.minute,
  });

  @override
  int get hashCode => enabled.hashCode ^ hour.hashCode ^ minute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DigestPrefs &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          hour == other.hour &&
          minute == other.minute;
}

/// 摘要计数（镜像 core digest_api::DigestSummary）
class DigestSummary {
  final PlatformInt64 dueToday;
  final PlatformInt64 overdue;
  final PlatformInt64 doneToday;

  const DigestSummary({
    required this.dueToday,
    required this.overdue,
    required this.doneToday,
  });

  @override
  int get hashCode => dueToday.hashCode ^ overdue.hashCode ^ doneToday.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DigestSummary &&
          runtimeType == other.runtimeType &&
          dueToday == other.dueToday &&
          overdue == other.overdue &&
          doneToday == other.doneToday;
}
