// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// 活动日志行（todo_activity_log 为本地轨迹表，不进同步白名单）
class ActivityLogRow {
  final PlatformInt64 id;
  final PlatformInt64? taskId;

  /// 任务标题快照（任务删除后仍可读）
  final String taskTitle;
  final String action;

  /// 附加 JSON：{"fields"/"changes"/"label"/"target"} 四代形状（格式化在 Dart 侧）
  final String detail;

  /// 记录时间（ms）
  final PlatformInt64 createdAt;

  const ActivityLogRow({
    required this.id,
    this.taskId,
    required this.taskTitle,
    required this.action,
    required this.detail,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      taskId.hashCode ^
      taskTitle.hashCode ^
      action.hashCode ^
      detail.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityLogRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          taskId == other.taskId &&
          taskTitle == other.taskTitle &&
          action == other.action &&
          detail == other.detail &&
          createdAt == other.createdAt;
}

/// 统一完成命令结果（镜像 orbit_core::api::todo_api::CompleteTaskResult；
/// 引擎下沉三端唯一完成入口：普通标记 / 重复任务单事务推进下一实例）
class CompleteTaskResult {
  final TodoTask task;

  /// 重复任务推进生成的下一实例（普通任务为 None）
  final TodoTask? nextInstance;

  const CompleteTaskResult({required this.task, this.nextInstance});

  @override
  int get hashCode => task.hashCode ^ nextInstance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompleteTaskResult &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          nextInstance == other.nextInstance;
}

/// 预览结果：前 N 行预览载荷 + 全量统计
class CsvImportPreviewView {
  final String preset;
  final List<CsvImportRowView> rows;
  final CsvImportStatsView stats;

  const CsvImportPreviewView({
    required this.preset,
    required this.rows,
    required this.stats,
  });

  @override
  int get hashCode => preset.hashCode ^ rows.hashCode ^ stats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvImportPreviewView &&
          runtimeType == other.runtimeType &&
          preset == other.preset &&
          rows == other.rows &&
          stats == other.stats;
}

/// 一条映射后的待导入行（预览载荷）
class CsvImportRowView {
  /// 源 CSV 行号（1 起，含表头）
  final BigInt sourceLine;

  /// 目标项目标题（None = 未分组；执行时按需自动建项目）
  final String? projectTitle;

  /// 待创建任务字段（部分填充）
  final TodoTaskCreateInput input;

  /// 跳过原因（Some = 本行不导入）
  final String? skipReason;

  const CsvImportRowView({
    required this.sourceLine,
    this.projectTitle,
    required this.input,
    this.skipReason,
  });

  @override
  int get hashCode =>
      sourceLine.hashCode ^
      projectTitle.hashCode ^
      input.hashCode ^
      skipReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvImportRowView &&
          runtimeType == other.runtimeType &&
          sourceLine == other.sourceLine &&
          projectTitle == other.projectTitle &&
          input == other.input &&
          skipReason == other.skipReason;
}

/// 导入统计（预览口径 success=待导入条数；执行口径=实际成功条数）
class CsvImportStatsView {
  final BigInt success;
  final BigInt skipped;
  final BigInt failed;

  /// 逐行错误/跳过说明（行号 + 原因）
  final List<String> notes;

  const CsvImportStatsView({
    required this.success,
    required this.skipped,
    required this.failed,
    required this.notes,
  });

  @override
  int get hashCode =>
      success.hashCode ^ skipped.hashCode ^ failed.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvImportStatsView &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          skipped == other.skipped &&
          failed == other.failed &&
          notes == other.notes;
}

/// 节假日行（core HolidayInfo 过桥镜像；FRB 字段级生成规则见模块注释）
class HolidayInfo {
  /// YYYY-MM-DD
  final String date;
  final int year;

  /// true = 放假日；false = 调休补班日（要上班的周末）
  final bool isHoliday;

  /// 节假日名称（如「春节」「春节前补班」）
  final String name;

  const HolidayInfo({
    required this.date,
    required this.year,
    required this.isHoliday,
    required this.name,
  });

  @override
  int get hashCode =>
      date.hashCode ^ year.hashCode ^ isHoliday.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HolidayInfo &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          year == other.year &&
          isHoliday == other.isHoliday &&
          name == other.name;
}

/// 节假日更新记账（上次更新时间/失败次数/固定时刻；日历工具栏展示用）
class HolidayMeta {
  /// 上次成功更新（ms；0 = 从未成功）
  final PlatformInt64 lastUpdateMs;

  /// 上次尝试（ms；0 = 从未尝试）
  final PlatformInt64 lastAttemptMs;

  /// 连续失败次数（成功后清零）
  final int failureCount;

  /// 每日固定更新时刻（本地时区小时 0-23；默认 8）
  final int fixedHour;

  const HolidayMeta({
    required this.lastUpdateMs,
    required this.lastAttemptMs,
    required this.failureCount,
    required this.fixedHour,
  });

  @override
  int get hashCode =>
      lastUpdateMs.hashCode ^
      lastAttemptMs.hashCode ^
      failureCount.hashCode ^
      fixedHour.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HolidayMeta &&
          runtimeType == other.runtimeType &&
          lastUpdateMs == other.lastUpdateMs &&
          lastAttemptMs == other.lastAttemptMs &&
          failureCount == other.failureCount &&
          fixedHour == other.fixedHour;
}

/// 通用列表过滤条件（镜像 orbit_core::models::business::ListFilter；
/// 谓词下推六键仅 todo_tasks 消费，见 core 侧注释）
class ListFilter {
  final String? keyword;
  final int page;
  final int pageSize;
  final bool? done;
  final String? status;
  final int? priorityMin;
  final PlatformInt64? projectId;
  final bool? favoriteOnly;
  final PlatformInt64? myDayToday;

  const ListFilter({
    this.keyword,
    required this.page,
    required this.pageSize,
    this.done,
    this.status,
    this.priorityMin,
    this.projectId,
    this.favoriteOnly,
    this.myDayToday,
  });

  @override
  int get hashCode =>
      keyword.hashCode ^
      page.hashCode ^
      pageSize.hashCode ^
      done.hashCode ^
      status.hashCode ^
      priorityMin.hashCode ^
      projectId.hashCode ^
      favoriteOnly.hashCode ^
      myDayToday.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListFilter &&
          runtimeType == other.runtimeType &&
          keyword == other.keyword &&
          page == other.page &&
          pageSize == other.pageSize &&
          done == other.done &&
          status == other.status &&
          priorityMin == other.priorityMin &&
          projectId == other.projectId &&
          favoriteOnly == other.favoriteOnly &&
          myDayToday == other.myDayToday;
}

/// 行内提醒最小载荷（镜像 ProjectedReminder）
class ProjectedReminder {
  final PlatformInt64 id;
  final PlatformInt64 remindAt;

  const ProjectedReminder({required this.id, required this.remindAt});

  @override
  int get hashCode => id.hashCode ^ remindAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectedReminder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          remindAt == other.remindAt;
}

/// 行内标签 chip 最小载荷（镜像 ProjectedTaskLabel：展示三列）
class ProjectedTaskLabel {
  final PlatformInt64 id;
  final String title;
  final String hexColor;

  const ProjectedTaskLabel({
    required this.id,
    required this.title,
    required this.hexColor,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ hexColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectedTaskLabel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          hexColor == other.hexColor;
}

/// 冲突败方副本（纯本地表，不随云同步；两个 payload 为整行字段快照 JSON 字符串）
class SyncConflict {
  final PlatformInt64 id;
  final String tableName;
  final String recordUuid;
  final String recordTitle;

  /// lww 时间戳裁决 / tie_version 同毫秒按 version 裁决
  final String decision;

  /// 败方归属：local 本地被覆盖 / remote 远端被丢弃
  final String loserSide;
  final String winnerSide;
  final String loserPayload;
  final String winnerPayload;
  final PlatformInt64 loserUpdatedAt;
  final PlatformInt64 winnerUpdatedAt;

  /// unresolved 未处理 / restored 已恢复 / dismissed 已忽略
  final String resolution;
  final PlatformInt64 createdAt;
  final PlatformInt64 resolvedAt;

  const SyncConflict({
    required this.id,
    required this.tableName,
    required this.recordUuid,
    required this.recordTitle,
    required this.decision,
    required this.loserSide,
    required this.winnerSide,
    required this.loserPayload,
    required this.winnerPayload,
    required this.loserUpdatedAt,
    required this.winnerUpdatedAt,
    required this.resolution,
    required this.createdAt,
    required this.resolvedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tableName.hashCode ^
      recordUuid.hashCode ^
      recordTitle.hashCode ^
      decision.hashCode ^
      loserSide.hashCode ^
      winnerSide.hashCode ^
      loserPayload.hashCode ^
      winnerPayload.hashCode ^
      loserUpdatedAt.hashCode ^
      winnerUpdatedAt.hashCode ^
      resolution.hashCode ^
      createdAt.hashCode ^
      resolvedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConflict &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tableName == other.tableName &&
          recordUuid == other.recordUuid &&
          recordTitle == other.recordTitle &&
          decision == other.decision &&
          loserSide == other.loserSide &&
          winnerSide == other.winnerSide &&
          loserPayload == other.loserPayload &&
          winnerPayload == other.winnerPayload &&
          loserUpdatedAt == other.loserUpdatedAt &&
          winnerUpdatedAt == other.winnerUpdatedAt &&
          resolution == other.resolution &&
          createdAt == other.createdAt &&
          resolvedAt == other.resolvedAt;
}

class TaskAttachmentView {
  final PlatformInt64 linkId;
  final String linkUuid;
  final String hash;
  final String originalName;
  final String mimeType;
  final PlatformInt64 sizeBytes;

  /// 0 = 尚未从云端拉回（云端有但本机未下载），UI 置灰打开入口
  final int isLocalCached;

  const TaskAttachmentView({
    required this.linkId,
    required this.linkUuid,
    required this.hash,
    required this.originalName,
    required this.mimeType,
    required this.sizeBytes,
    required this.isLocalCached,
  });

  @override
  int get hashCode =>
      linkId.hashCode ^
      linkUuid.hashCode ^
      hash.hashCode ^
      originalName.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      isLocalCached.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskAttachmentView &&
          runtimeType == other.runtimeType &&
          linkId == other.linkId &&
          linkUuid == other.linkUuid &&
          hash == other.hash &&
          originalName == other.originalName &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          isLocalCached == other.isLocalCached;
}

/// 单任务的关联计数旗标（镜像 TaskDependencyFlags；C7 行内关联徽标消费）
class TaskDependencyFlags {
  final PlatformInt64 taskId;

  /// 出边存活行总数（> 0 即「有关联」）
  final PlatformInt64 relationCount;

  const TaskDependencyFlags({
    required this.taskId,
    required this.relationCount,
  });

  @override
  int get hashCode => taskId.hashCode ^ relationCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDependencyFlags &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          relationCount == other.relationCount;
}

/// 「有描述」任务 id 位（镜像 TaskDescriptionFlag；列表通道裁剪 description
/// 后行内描述图标的来源，只出有描述的行）
class TaskDescriptionFlag {
  final PlatformInt64 taskId;

  const TaskDescriptionFlag({required this.taskId});

  @override
  int get hashCode => taskId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDescriptionFlag &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId;
}

/// 任务详情中的标签：TodoLabel 全部字段 + task_label_id
///
/// core 版（orbit_core::api::todo_api::TaskLabelWithId）用
/// `#[serde(flatten)] label: TodoLabel`，JSON 为扁平形状；此处直接平铺。
class TaskLabelWithId {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String hexColor;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  /// todo_task_labels 关联记录自身 id（移除关联时用）
  final PlatformInt64 taskLabelId;

  const TaskLabelWithId({
    required this.id,
    required this.uuid,
    required this.title,
    required this.hexColor,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
    required this.taskLabelId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      hexColor.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode ^
      taskLabelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskLabelWithId &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          hexColor == other.hexColor &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version &&
          taskLabelId == other.taskLabelId;
}

/// 单任务的标签分组（镜像 TaskLabelsProjection）
class TaskLabelsProjection {
  final PlatformInt64 taskId;
  final List<ProjectedTaskLabel> labels;

  const TaskLabelsProjection({required this.taskId, required this.labels});

  @override
  int get hashCode => taskId.hashCode ^ labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskLabelsProjection &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          labels == other.labels;
}

/// 单任务的提醒分组（镜像 TaskRemindersProjection）
class TaskRemindersProjection {
  final PlatformInt64 taskId;
  final List<ProjectedReminder> reminders;

  const TaskRemindersProjection({
    required this.taskId,
    required this.reminders,
  });

  @override
  int get hashCode => taskId.hashCode ^ reminders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskRemindersProjection &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          reminders == other.reminders;
}

/// 评论（镜像 orbit_core::models::business::TodoComment）
class TodoComment {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final String content;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoComment({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.content,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      content.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoComment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          content == other.content &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 评论创建输入（镜像 TodoCommentCreateInput）
class TodoCommentCreateInput {
  final PlatformInt64 taskId;
  final String content;

  const TodoCommentCreateInput({required this.taskId, required this.content});

  @override
  int get hashCode => taskId.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoCommentCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          content == other.content;
}

/// 标签（镜像 orbit_core::models::business::TodoLabel）
class TodoLabel {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String hexColor;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoLabel({
    required this.id,
    required this.uuid,
    required this.title,
    required this.hexColor,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      hexColor.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoLabel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          hexColor == other.hexColor &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 标签创建输入（镜像 TodoLabelCreateInput）
class TodoLabelCreateInput {
  final String title;
  final String? hexColor;

  const TodoLabelCreateInput({required this.title, this.hexColor});

  @override
  int get hashCode => title.hashCode ^ hexColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoLabelCreateInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          hexColor == other.hexColor;
}

/// 项目（镜像 orbit_core::models::business::TodoProject）
class TodoProject {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String? description;
  final String hexColor;
  final double sortOrder;
  final int isArchived;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoProject({
    required this.id,
    required this.uuid,
    required this.title,
    this.description,
    required this.hexColor,
    required this.sortOrder,
    required this.isArchived,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      hexColor.hashCode ^
      sortOrder.hashCode ^
      isArchived.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoProject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          description == other.description &&
          hexColor == other.hexColor &&
          sortOrder == other.sortOrder &&
          isArchived == other.isArchived &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 项目创建输入（镜像 TodoProjectCreateInput；create input 均为普通
/// Option<T>/T，无三态字段，可直接一一映射）
class TodoProjectCreateInput {
  final String title;
  final String? description;
  final String? hexColor;
  final double? sortOrder;

  const TodoProjectCreateInput({
    required this.title,
    this.description,
    this.hexColor,
    this.sortOrder,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      hexColor.hashCode ^
      sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoProjectCreateInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          hexColor == other.hexColor &&
          sortOrder == other.sortOrder;
}

/// 提醒（镜像 orbit_core::models::business::TodoReminder）
class TodoReminder {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final PlatformInt64 remindAt;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoReminder({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.remindAt,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      remindAt.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoReminder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          remindAt == other.remindAt &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 提醒创建输入（镜像 TodoReminderCreateInput）
class TodoReminderCreateInput {
  final PlatformInt64 taskId;
  final PlatformInt64 remindAt;

  const TodoReminderCreateInput({required this.taskId, required this.remindAt});

  @override
  int get hashCode => taskId.hashCode ^ remindAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoReminderCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          remindAt == other.remindAt;
}

class TodoSavedFilter {
  final PlatformInt64 id;
  final String uuid;
  final String name;

  /// 条件 JSON：{status?, priority_min?, project_ids?, label_ids?, due_within_days?, due_overdue?, favorite_only?}
  final String conditions;
  final PlatformInt64 sortOrder;

  const TodoSavedFilter({
    required this.id,
    required this.uuid,
    required this.name,
    required this.conditions,
    required this.sortOrder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      name.hashCode ^
      conditions.hashCode ^
      sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSavedFilter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          name == other.name &&
          conditions == other.conditions &&
          sortOrder == other.sortOrder;
}

class TodoSavedFilterCreateInput {
  final String name;
  final String conditions;
  final PlatformInt64? sortOrder;

  const TodoSavedFilterCreateInput({
    required this.name,
    required this.conditions,
    this.sortOrder,
  });

  @override
  int get hashCode => name.hashCode ^ conditions.hashCode ^ sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSavedFilterCreateInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          conditions == other.conditions &&
          sortOrder == other.sortOrder;
}

class TodoSavedFilterUpdateInput {
  final String? name;
  final String? conditions;
  final PlatformInt64? sortOrder;

  const TodoSavedFilterUpdateInput({
    this.name,
    this.conditions,
    this.sortOrder,
  });

  @override
  int get hashCode => name.hashCode ^ conditions.hashCode ^ sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSavedFilterUpdateInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          conditions == other.conditions &&
          sortOrder == other.sortOrder;
}

/// 子任务（镜像 orbit_core::models::business::TodoSubtask）
class TodoSubtask {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final String title;
  final int done;
  final PlatformInt64? doneAt;
  final double position;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoSubtask({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.title,
    required this.done,
    this.doneAt,
    required this.position,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      title.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      position.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSubtask &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          title == other.title &&
          done == other.done &&
          doneAt == other.doneAt &&
          position == other.position &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 子任务创建输入（镜像 TodoSubtaskCreateInput）
class TodoSubtaskCreateInput {
  final PlatformInt64 taskId;
  final String title;
  final double? position;

  const TodoSubtaskCreateInput({
    required this.taskId,
    required this.title,
    this.position,
  });

  @override
  int get hashCode => taskId.hashCode ^ title.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSubtaskCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          title == other.title &&
          position == other.position;
}

/// 任务（镜像 orbit_core::models::business::TodoTask）
class TodoTask {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String? description;
  final PlatformInt64? projectId;
  final int priority;
  final String status;
  final int done;
  final PlatformInt64? doneAt;
  final PlatformInt64? dueDate;
  final PlatformInt64? startDate;
  final PlatformInt64 repeatAfter;
  final int repeatMode;

  /// #34 重复规则扩展（与 orbit-core TodoTask 同名列镜像）
  final int repeatWeekdays;
  final int repeatEndType;
  final PlatformInt64 repeatEndParam;
  final int repeatFromDone;
  final double percentDone;
  final double position;
  final int isFavorite;
  final PlatformInt64? myDayDate;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoTask({
    required this.id,
    required this.uuid,
    required this.title,
    this.description,
    this.projectId,
    required this.priority,
    required this.status,
    required this.done,
    this.doneAt,
    this.dueDate,
    this.startDate,
    required this.repeatAfter,
    required this.repeatMode,
    required this.repeatWeekdays,
    required this.repeatEndType,
    required this.repeatEndParam,
    required this.repeatFromDone,
    required this.percentDone,
    required this.position,
    required this.isFavorite,
    this.myDayDate,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      projectId.hashCode ^
      priority.hashCode ^
      status.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      dueDate.hashCode ^
      startDate.hashCode ^
      repeatAfter.hashCode ^
      repeatMode.hashCode ^
      repeatWeekdays.hashCode ^
      repeatEndType.hashCode ^
      repeatEndParam.hashCode ^
      repeatFromDone.hashCode ^
      percentDone.hashCode ^
      position.hashCode ^
      isFavorite.hashCode ^
      myDayDate.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTask &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          description == other.description &&
          projectId == other.projectId &&
          priority == other.priority &&
          status == other.status &&
          done == other.done &&
          doneAt == other.doneAt &&
          dueDate == other.dueDate &&
          startDate == other.startDate &&
          repeatAfter == other.repeatAfter &&
          repeatMode == other.repeatMode &&
          repeatWeekdays == other.repeatWeekdays &&
          repeatEndType == other.repeatEndType &&
          repeatEndParam == other.repeatEndParam &&
          repeatFromDone == other.repeatFromDone &&
          percentDone == other.percentDone &&
          position == other.position &&
          isFavorite == other.isFavorite &&
          myDayDate == other.myDayDate &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 任务创建输入（镜像 TodoTaskCreateInput；均为普通 Option<T>/T 字段）
///
/// 注：core 的 `TodoTaskUpdateInput` 才含 `Option<Option<T>>` 可空列
/// （project_id/done_at/due_date/start_date 等），不在此镜像，
/// 走 patch_json 路径。
class TodoTaskCreateInput {
  final String title;
  final String? description;
  final PlatformInt64? projectId;
  final int? priority;
  final String? status;
  final int? done;
  final PlatformInt64? doneAt;
  final PlatformInt64? dueDate;
  final PlatformInt64? startDate;
  final PlatformInt64? repeatAfter;
  final int? repeatMode;
  final int? repeatWeekdays;
  final int? repeatEndType;
  final PlatformInt64? repeatEndParam;
  final int? repeatFromDone;
  final double? position;
  final int? isFavorite;
  final PlatformInt64? myDayDate;

  const TodoTaskCreateInput({
    required this.title,
    this.description,
    this.projectId,
    this.priority,
    this.status,
    this.done,
    this.doneAt,
    this.dueDate,
    this.startDate,
    this.repeatAfter,
    this.repeatMode,
    this.repeatWeekdays,
    this.repeatEndType,
    this.repeatEndParam,
    this.repeatFromDone,
    this.position,
    this.isFavorite,
    this.myDayDate,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      projectId.hashCode ^
      priority.hashCode ^
      status.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      dueDate.hashCode ^
      startDate.hashCode ^
      repeatAfter.hashCode ^
      repeatMode.hashCode ^
      repeatWeekdays.hashCode ^
      repeatEndType.hashCode ^
      repeatEndParam.hashCode ^
      repeatFromDone.hashCode ^
      position.hashCode ^
      isFavorite.hashCode ^
      myDayDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskCreateInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          projectId == other.projectId &&
          priority == other.priority &&
          status == other.status &&
          done == other.done &&
          doneAt == other.doneAt &&
          dueDate == other.dueDate &&
          startDate == other.startDate &&
          repeatAfter == other.repeatAfter &&
          repeatMode == other.repeatMode &&
          repeatWeekdays == other.repeatWeekdays &&
          repeatEndType == other.repeatEndType &&
          repeatEndParam == other.repeatEndParam &&
          repeatFromDone == other.repeatFromDone &&
          position == other.position &&
          isFavorite == other.isFavorite &&
          myDayDate == other.myDayDate;
}

/// 任务详情聚合：TodoTask 全部字段 + 五张子表 Vec
///
/// core 版（orbit_core::api::todo_api::TodoTaskDetail）用
/// `#[serde(flatten)] task: TodoTask`，JSON 为扁平形状（与桌面 Tauri 契约、
/// 移动端 data/api/dto.dart 的 `TodoTaskDetail extends TodoTask` 一致）；
/// 此处平铺 task 字段，避免 Dart 侧出现嵌套差异。
class TodoTaskDetail {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String? description;
  final PlatformInt64? projectId;
  final int priority;
  final String status;
  final int done;
  final PlatformInt64? doneAt;
  final PlatformInt64? dueDate;
  final PlatformInt64? startDate;
  final PlatformInt64 repeatAfter;
  final int repeatMode;

  /// #34 重复规则扩展（与 orbit-core TodoTask 同名列镜像）
  final int repeatWeekdays;
  final int repeatEndType;
  final PlatformInt64 repeatEndParam;
  final int repeatFromDone;
  final double percentDone;
  final double position;
  final int isFavorite;
  final PlatformInt64? myDayDate;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;
  final List<TodoSubtask> subtasks;
  final List<TaskLabelWithId> labels;
  final List<TodoComment> comments;
  final List<TodoTaskRelation> relations;
  final List<TodoReminder> reminders;

  const TodoTaskDetail({
    required this.id,
    required this.uuid,
    required this.title,
    this.description,
    this.projectId,
    required this.priority,
    required this.status,
    required this.done,
    this.doneAt,
    this.dueDate,
    this.startDate,
    required this.repeatAfter,
    required this.repeatMode,
    required this.repeatWeekdays,
    required this.repeatEndType,
    required this.repeatEndParam,
    required this.repeatFromDone,
    required this.percentDone,
    required this.position,
    required this.isFavorite,
    this.myDayDate,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
    required this.subtasks,
    required this.labels,
    required this.comments,
    required this.relations,
    required this.reminders,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      projectId.hashCode ^
      priority.hashCode ^
      status.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      dueDate.hashCode ^
      startDate.hashCode ^
      repeatAfter.hashCode ^
      repeatMode.hashCode ^
      repeatWeekdays.hashCode ^
      repeatEndType.hashCode ^
      repeatEndParam.hashCode ^
      repeatFromDone.hashCode ^
      percentDone.hashCode ^
      position.hashCode ^
      isFavorite.hashCode ^
      myDayDate.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode ^
      subtasks.hashCode ^
      labels.hashCode ^
      comments.hashCode ^
      relations.hashCode ^
      reminders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          description == other.description &&
          projectId == other.projectId &&
          priority == other.priority &&
          status == other.status &&
          done == other.done &&
          doneAt == other.doneAt &&
          dueDate == other.dueDate &&
          startDate == other.startDate &&
          repeatAfter == other.repeatAfter &&
          repeatMode == other.repeatMode &&
          repeatWeekdays == other.repeatWeekdays &&
          repeatEndType == other.repeatEndType &&
          repeatEndParam == other.repeatEndParam &&
          repeatFromDone == other.repeatFromDone &&
          percentDone == other.percentDone &&
          position == other.position &&
          isFavorite == other.isFavorite &&
          myDayDate == other.myDayDate &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version &&
          subtasks == other.subtasks &&
          labels == other.labels &&
          comments == other.comments &&
          relations == other.relations &&
          reminders == other.reminders;
}

/// 任务↔标签关联（镜像 orbit_core::models::business::TodoTaskLabel）
class TodoTaskLabel {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final PlatformInt64 labelId;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoTaskLabel({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.labelId,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      labelId.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskLabel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          labelId == other.labelId &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 关联创建输入（镜像 TodoTaskLabelCreateInput）
class TodoTaskLabelCreateInput {
  final PlatformInt64 taskId;
  final PlatformInt64 labelId;

  const TodoTaskLabelCreateInput({required this.taskId, required this.labelId});

  @override
  int get hashCode => taskId.hashCode ^ labelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskLabelCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          labelId == other.labelId;
}

/// 任务关系（镜像 orbit_core::models::business::TodoTaskRelation）
class TodoTaskRelation {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final PlatformInt64 otherTaskId;
  final String relationType;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoTaskRelation({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.otherTaskId,
    required this.relationType,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      otherTaskId.hashCode ^
      relationType.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskRelation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          otherTaskId == other.otherTaskId &&
          relationType == other.relationType &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 关系创建输入（镜像 TodoTaskRelationCreateInput）
class TodoTaskRelationCreateInput {
  final PlatformInt64 taskId;
  final PlatformInt64 otherTaskId;
  final String relationType;

  const TodoTaskRelationCreateInput({
    required this.taskId,
    required this.otherTaskId,
    required this.relationType,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^ otherTaskId.hashCode ^ relationType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskRelationCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          otherTaskId == other.otherTaskId &&
          relationType == other.relationType;
}

class TodoTemplate {
  final PlatformInt64 id;
  final String uuid;
  final String name;

  /// 模板内容 JSON：{title?, notes?, priority?, due_offset_days?, subtasks?}——套用时按存在键预填
  final String payload;
  final PlatformInt64 sortOrder;

  const TodoTemplate({
    required this.id,
    required this.uuid,
    required this.name,
    required this.payload,
    required this.sortOrder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      name.hashCode ^
      payload.hashCode ^
      sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTemplate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          name == other.name &&
          payload == other.payload &&
          sortOrder == other.sortOrder;
}

class TodoTemplateCreateInput {
  final String name;
  final String payload;
  final PlatformInt64? sortOrder;

  const TodoTemplateCreateInput({
    required this.name,
    required this.payload,
    this.sortOrder,
  });

  @override
  int get hashCode => name.hashCode ^ payload.hashCode ^ sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTemplateCreateInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          payload == other.payload &&
          sortOrder == other.sortOrder;
}

class TodoTemplateUpdateInput {
  final String? name;
  final String? payload;
  final PlatformInt64? sortOrder;

  const TodoTemplateUpdateInput({this.name, this.payload, this.sortOrder});

  @override
  int get hashCode => name.hashCode ^ payload.hashCode ^ sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTemplateUpdateInput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          payload == other.payload &&
          sortOrder == other.sortOrder;
}
