// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// 通用列表过滤条件（镜像 orbit_core::models::business::ListFilter）
class ListFilter {
  final String? keyword;
  final int page;
  final int pageSize;

  const ListFilter({this.keyword, required this.page, required this.pageSize});

  @override
  int get hashCode => keyword.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListFilter &&
          runtimeType == other.runtimeType &&
          keyword == other.keyword &&
          page == other.page &&
          pageSize == other.pageSize;
}

/// 任务详情中的标签：TodoLabel 全部字段 + task_label_id
///
/// core 版（orbit_core::api::todo_api::TaskLabelWithId）用
/// `#[serde(flatten)] label: TodoLabel`，JSON 为扁平形状；此处直接平铺。
class TaskLabelWithId {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String hexColor;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  /// todo_task_labels 关联记录自身 id（移除关联时用）
  final PlatformInt64 taskLabelId;

  const TaskLabelWithId({
    required this.id,
    required this.uuid,
    required this.title,
    required this.hexColor,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
    required this.taskLabelId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      hexColor.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode ^
      taskLabelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskLabelWithId &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          hexColor == other.hexColor &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version &&
          taskLabelId == other.taskLabelId;
}

/// 评论（镜像 orbit_core::models::business::TodoComment）
class TodoComment {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final String content;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoComment({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.content,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      content.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoComment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          content == other.content &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 评论创建输入（镜像 TodoCommentCreateInput）
class TodoCommentCreateInput {
  final PlatformInt64 taskId;
  final String content;

  const TodoCommentCreateInput({required this.taskId, required this.content});

  @override
  int get hashCode => taskId.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoCommentCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          content == other.content;
}

/// 标签（镜像 orbit_core::models::business::TodoLabel）
class TodoLabel {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String hexColor;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoLabel({
    required this.id,
    required this.uuid,
    required this.title,
    required this.hexColor,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      hexColor.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoLabel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          hexColor == other.hexColor &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 标签创建输入（镜像 TodoLabelCreateInput）
class TodoLabelCreateInput {
  final String title;
  final String? hexColor;

  const TodoLabelCreateInput({required this.title, this.hexColor});

  @override
  int get hashCode => title.hashCode ^ hexColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoLabelCreateInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          hexColor == other.hexColor;
}

/// 项目（镜像 orbit_core::models::business::TodoProject）
class TodoProject {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String? description;
  final String hexColor;
  final double sortOrder;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoProject({
    required this.id,
    required this.uuid,
    required this.title,
    this.description,
    required this.hexColor,
    required this.sortOrder,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      hexColor.hashCode ^
      sortOrder.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoProject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          description == other.description &&
          hexColor == other.hexColor &&
          sortOrder == other.sortOrder &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 项目创建输入（镜像 TodoProjectCreateInput；create input 均为普通
/// Option<T>/T，无三态字段，可直接一一映射）
class TodoProjectCreateInput {
  final String title;
  final String? description;
  final String? hexColor;
  final double? sortOrder;

  const TodoProjectCreateInput({
    required this.title,
    this.description,
    this.hexColor,
    this.sortOrder,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      hexColor.hashCode ^
      sortOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoProjectCreateInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          hexColor == other.hexColor &&
          sortOrder == other.sortOrder;
}

/// 提醒（镜像 orbit_core::models::business::TodoReminder）
class TodoReminder {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final PlatformInt64 remindAt;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoReminder({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.remindAt,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      remindAt.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoReminder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          remindAt == other.remindAt &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 提醒创建输入（镜像 TodoReminderCreateInput）
class TodoReminderCreateInput {
  final PlatformInt64 taskId;
  final PlatformInt64 remindAt;

  const TodoReminderCreateInput({required this.taskId, required this.remindAt});

  @override
  int get hashCode => taskId.hashCode ^ remindAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoReminderCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          remindAt == other.remindAt;
}

/// 子任务（镜像 orbit_core::models::business::TodoSubtask）
class TodoSubtask {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final String title;
  final int done;
  final PlatformInt64? doneAt;
  final double position;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoSubtask({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.title,
    required this.done,
    this.doneAt,
    required this.position,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      title.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      position.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSubtask &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          title == other.title &&
          done == other.done &&
          doneAt == other.doneAt &&
          position == other.position &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 子任务创建输入（镜像 TodoSubtaskCreateInput）
class TodoSubtaskCreateInput {
  final PlatformInt64 taskId;
  final String title;
  final double? position;

  const TodoSubtaskCreateInput({
    required this.taskId,
    required this.title,
    this.position,
  });

  @override
  int get hashCode => taskId.hashCode ^ title.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoSubtaskCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          title == other.title &&
          position == other.position;
}

/// 任务（镜像 orbit_core::models::business::TodoTask）
class TodoTask {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String? description;
  final PlatformInt64? projectId;
  final int priority;
  final String status;
  final int done;
  final PlatformInt64? doneAt;
  final PlatformInt64? dueDate;
  final PlatformInt64? startDate;
  final PlatformInt64? endDate;
  final PlatformInt64 repeatAfter;
  final int repeatMode;
  final String hexColor;
  final double percentDone;
  final double position;
  final int isFavorite;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoTask({
    required this.id,
    required this.uuid,
    required this.title,
    this.description,
    this.projectId,
    required this.priority,
    required this.status,
    required this.done,
    this.doneAt,
    this.dueDate,
    this.startDate,
    this.endDate,
    required this.repeatAfter,
    required this.repeatMode,
    required this.hexColor,
    required this.percentDone,
    required this.position,
    required this.isFavorite,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      projectId.hashCode ^
      priority.hashCode ^
      status.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      dueDate.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      repeatAfter.hashCode ^
      repeatMode.hashCode ^
      hexColor.hashCode ^
      percentDone.hashCode ^
      position.hashCode ^
      isFavorite.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTask &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          description == other.description &&
          projectId == other.projectId &&
          priority == other.priority &&
          status == other.status &&
          done == other.done &&
          doneAt == other.doneAt &&
          dueDate == other.dueDate &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          repeatAfter == other.repeatAfter &&
          repeatMode == other.repeatMode &&
          hexColor == other.hexColor &&
          percentDone == other.percentDone &&
          position == other.position &&
          isFavorite == other.isFavorite &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 任务创建输入（镜像 TodoTaskCreateInput；均为普通 Option<T>/T 字段）
///
/// 注：core 的 `TodoTaskUpdateInput` 才含 `Option<Option<T>>` 可空列
/// （project_id/done_at/due_date/start_date/end_date 等），不在此镜像，
/// 走 patch_json 路径。
class TodoTaskCreateInput {
  final String title;
  final String? description;
  final PlatformInt64? projectId;
  final int? priority;
  final String? status;
  final int? done;
  final PlatformInt64? doneAt;
  final PlatformInt64? dueDate;
  final PlatformInt64? startDate;
  final PlatformInt64? endDate;
  final PlatformInt64? repeatAfter;
  final int? repeatMode;
  final String? hexColor;
  final double? position;
  final int? isFavorite;

  const TodoTaskCreateInput({
    required this.title,
    this.description,
    this.projectId,
    this.priority,
    this.status,
    this.done,
    this.doneAt,
    this.dueDate,
    this.startDate,
    this.endDate,
    this.repeatAfter,
    this.repeatMode,
    this.hexColor,
    this.position,
    this.isFavorite,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      projectId.hashCode ^
      priority.hashCode ^
      status.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      dueDate.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      repeatAfter.hashCode ^
      repeatMode.hashCode ^
      hexColor.hashCode ^
      position.hashCode ^
      isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskCreateInput &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          projectId == other.projectId &&
          priority == other.priority &&
          status == other.status &&
          done == other.done &&
          doneAt == other.doneAt &&
          dueDate == other.dueDate &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          repeatAfter == other.repeatAfter &&
          repeatMode == other.repeatMode &&
          hexColor == other.hexColor &&
          position == other.position &&
          isFavorite == other.isFavorite;
}

/// 任务详情聚合：TodoTask 全部字段 + 五张子表 Vec
///
/// core 版（orbit_core::api::todo_api::TodoTaskDetail）用
/// `#[serde(flatten)] task: TodoTask`，JSON 为扁平形状（与桌面 Tauri 契约、
/// 移动端 data/api/dto.dart 的 `TodoTaskDetail extends TodoTask` 一致）；
/// 此处平铺 task 字段，避免 Dart 侧出现嵌套差异。
class TodoTaskDetail {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final String? description;
  final PlatformInt64? projectId;
  final int priority;
  final String status;
  final int done;
  final PlatformInt64? doneAt;
  final PlatformInt64? dueDate;
  final PlatformInt64? startDate;
  final PlatformInt64? endDate;
  final PlatformInt64 repeatAfter;
  final int repeatMode;
  final String hexColor;
  final double percentDone;
  final double position;
  final int isFavorite;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;
  final List<TodoSubtask> subtasks;
  final List<TaskLabelWithId> labels;
  final List<TodoComment> comments;
  final List<TodoTaskRelation> relations;
  final List<TodoReminder> reminders;

  const TodoTaskDetail({
    required this.id,
    required this.uuid,
    required this.title,
    this.description,
    this.projectId,
    required this.priority,
    required this.status,
    required this.done,
    this.doneAt,
    this.dueDate,
    this.startDate,
    this.endDate,
    required this.repeatAfter,
    required this.repeatMode,
    required this.hexColor,
    required this.percentDone,
    required this.position,
    required this.isFavorite,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
    required this.subtasks,
    required this.labels,
    required this.comments,
    required this.relations,
    required this.reminders,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      projectId.hashCode ^
      priority.hashCode ^
      status.hashCode ^
      done.hashCode ^
      doneAt.hashCode ^
      dueDate.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      repeatAfter.hashCode ^
      repeatMode.hashCode ^
      hexColor.hashCode ^
      percentDone.hashCode ^
      position.hashCode ^
      isFavorite.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode ^
      subtasks.hashCode ^
      labels.hashCode ^
      comments.hashCode ^
      relations.hashCode ^
      reminders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          description == other.description &&
          projectId == other.projectId &&
          priority == other.priority &&
          status == other.status &&
          done == other.done &&
          doneAt == other.doneAt &&
          dueDate == other.dueDate &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          repeatAfter == other.repeatAfter &&
          repeatMode == other.repeatMode &&
          hexColor == other.hexColor &&
          percentDone == other.percentDone &&
          position == other.position &&
          isFavorite == other.isFavorite &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version &&
          subtasks == other.subtasks &&
          labels == other.labels &&
          comments == other.comments &&
          relations == other.relations &&
          reminders == other.reminders;
}

/// 任务↔标签关联（镜像 orbit_core::models::business::TodoTaskLabel）
class TodoTaskLabel {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final PlatformInt64 labelId;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoTaskLabel({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.labelId,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      labelId.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskLabel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          labelId == other.labelId &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 关联创建输入（镜像 TodoTaskLabelCreateInput）
class TodoTaskLabelCreateInput {
  final PlatformInt64 taskId;
  final PlatformInt64 labelId;

  const TodoTaskLabelCreateInput({required this.taskId, required this.labelId});

  @override
  int get hashCode => taskId.hashCode ^ labelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskLabelCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          labelId == other.labelId;
}

/// 任务关系（镜像 orbit_core::models::business::TodoTaskRelation）
class TodoTaskRelation {
  final PlatformInt64 id;
  final String uuid;
  final PlatformInt64 taskId;
  final PlatformInt64 otherTaskId;
  final String relationType;
  final int isDeleted;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? deletedAt;
  final int version;

  const TodoTaskRelation({
    required this.id,
    required this.uuid,
    required this.taskId,
    required this.otherTaskId,
    required this.relationType,
    required this.isDeleted,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.version,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      taskId.hashCode ^
      otherTaskId.hashCode ^
      relationType.hashCode ^
      isDeleted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deletedAt.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskRelation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          taskId == other.taskId &&
          otherTaskId == other.otherTaskId &&
          relationType == other.relationType &&
          isDeleted == other.isDeleted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt &&
          version == other.version;
}

/// 关系创建输入（镜像 TodoTaskRelationCreateInput）
class TodoTaskRelationCreateInput {
  final PlatformInt64 taskId;
  final PlatformInt64 otherTaskId;
  final String relationType;

  const TodoTaskRelationCreateInput({
    required this.taskId,
    required this.otherTaskId,
    required this.relationType,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^ otherTaskId.hashCode ^ relationType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoTaskRelationCreateInput &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          otherTaskId == other.otherTaskId &&
          relationType == other.relationType;
}
