// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `poll_once`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `from`

/// 订阅数据库变更流（db-change）
///
/// Dart 侧消费：收到即全量失效业务缓存（对齐桌面粗粒度失效策略）。
Stream<DbEventDto> subscribeDbChanges() =>
    RustLib.instance.api.crateApiEventsSubscribeDbChanges();

/// 启动待办提醒轮询守护（幂等；Dart 在 DB 就绪后调用一次）
///
/// 扫描口径与桌面一致：
/// `WHERE is_deleted=0 AND remind_at <= now AND now - remind_at <= 24h`
Stream<ReminderDueDto> startReminderPoller() =>
    RustLib.instance.api.crateApiEventsStartReminderPoller();

/// 数据库变更事件载荷（对齐桌面 TS DbChangeEvent 接口）
class DbEventDto {
  final String table;

  /// 变体名（"Insert"/"Update"/"Delete"/"Sync"，与桌面 serde 序列化一致）
  final String op;
  final PlatformInt64 recordId;
  final String recordUuid;
  final String deviceId;
  final PlatformInt64 timestamp;

  const DbEventDto({
    required this.table,
    required this.op,
    required this.recordId,
    required this.recordUuid,
    required this.deviceId,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      table.hashCode ^
      op.hashCode ^
      recordId.hashCode ^
      recordUuid.hashCode ^
      deviceId.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbEventDto &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          op == other.op &&
          recordId == other.recordId &&
          recordUuid == other.recordUuid &&
          deviceId == other.deviceId &&
          timestamp == other.timestamp;
}

/// 提醒到期事件载荷（对齐桌面 notification_scheduler ReminderDueEvent）
class ReminderDueDto {
  final PlatformInt64 id;
  final PlatformInt64 taskId;
  final String title;
  final PlatformInt64 remindAt;

  const ReminderDueDto({
    required this.id,
    required this.taskId,
    required this.title,
    required this.remindAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ taskId.hashCode ^ title.hashCode ^ remindAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReminderDueDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          taskId == other.taskId &&
          title == other.title &&
          remindAt == other.remindAt;
}
