// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_cloud_config`, `base_dir`, `emit_full_change`, `from_map`, `parse_schedule_type`, `schedule_type_str`, `tick_once`, `to_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

/// 导出全量备份到 `{base_dir}/backups/`，`upload_cloud` 时额外上传云端副本
///
/// 手动导出（origin=Manual）不受自动备份偏好开关约束；密码复用已解锁态缓存，
/// 前端须先完成同步密码解锁。
Future<BackupExportResult> fullBackupExport({required bool uploadCloud}) =>
    RustLib.instance.api.crateApiFullSyncBackupFullBackupExport(
      uploadCloud: uploadCloud,
    );

/// 从 `.orfullsync` 字节全量覆盖恢复（兼容遗留 `.waitfullsync` / `.orsync`）
///
/// 警示语义：导入会清空当前业务表再写入备份内容（事务内原子完成）。
/// 成功后广播 db-change（table="*"）触发前端全量刷新。
Future<BackupImportResult> fullBackupImport({
  required List<int> bytes,
  required bool ignoreSchemaMismatch,
}) => RustLib.instance.api.crateApiFullSyncBackupFullBackupImport(
  bytes: bytes,
  ignoreSchemaMismatch: ignoreSchemaMismatch,
);

/// 从云端备份副本全量覆盖恢复（先下载字节，再走与本地一致的导入路径）
Future<BackupImportResult> fullBackupRestoreCloud({
  required String cloudPath,
  required bool ignoreSchemaMismatch,
}) => RustLib.instance.api.crateApiFullSyncBackupFullBackupRestoreCloud(
  cloudPath: cloudPath,
  ignoreSchemaMismatch: ignoreSchemaMismatch,
);

/// 列出本地 backups 目录的历史备份（最新在前）
Future<List<BackupEntryView>> fullBackupListLocal() =>
    RustLib.instance.api.crateApiFullSyncBackupFullBackupListLocal();

/// 删除指定本地备份文件
Future<void> fullBackupDeleteLocal({required String filePath}) => RustLib
    .instance
    .api
    .crateApiFullSyncBackupFullBackupDeleteLocal(filePath: filePath);

/// 列出当前激活云空间 `backups/` 目录下的历史备份副本（最新在前）
Future<List<CloudBackupEntryView>> fullBackupListCloud() =>
    RustLib.instance.api.crateApiFullSyncBackupFullBackupListCloud();

/// 读取本地备份恢复预览（解密 + 前 10 条任务抽样 + 统计，不写库）
Future<BackupPreviewView> fullBackupPeekLocal({required List<int> bytes}) =>
    RustLib.instance.api.crateApiFullSyncBackupFullBackupPeekLocal(
      bytes: bytes,
    );

/// 读取云端备份恢复预览（先下载字节，再走与本地一致的预览路径，不写库）
Future<BackupPreviewView> fullBackupPeekCloud({required String cloudPath}) =>
    RustLib.instance.api.crateApiFullSyncBackupFullBackupPeekCloud(
      cloudPath: cloudPath,
    );

/// 当前设备 ID（导出预览展示用；未初始化返回空串）
Future<BackupDeviceInfo> fullBackupDeviceInfo() =>
    RustLib.instance.api.crateApiFullSyncBackupFullBackupDeviceInfo();

/// 读取备份偏好（无文件返回默认值：off + 本地开关开 + 云端开关开）
Future<BackupPrefsView> backupPrefsGet() =>
    RustLib.instance.api.crateApiFullSyncBackupBackupPrefsGet();

/// 保存备份偏好（校验调度配置；返回回填 next_backup_at 后的完整偏好）
///
/// 调度变更时统一重算 next_backup_at：off → 0（取消调度），
/// 其余 → 从当前时间起算的下一次触发点（与桌面 backup_prefs_save 同口径）。
Future<BackupPrefsView> backupPrefsSave({required BackupPrefsView prefs}) =>
    RustLib.instance.api.crateApiFullSyncBackupBackupPrefsSave(prefs: prefs);

/// 启动定时全量备份守护（幂等；Dart 在 DB 就绪后调用一次，BootGate 接线）
///
/// 移动端无跨重启用持久凭据，未解锁同步密码时导出返回可读错误——
/// 守护仅推进 next_backup_at，不打扰用户。
Future<void> startBackupScheduler() =>
    RustLib.instance.api.crateApiFullSyncBackupStartBackupScheduler();

/// 设备信息（导出预览展示用）
class BackupDeviceInfo {
  final String deviceId;

  const BackupDeviceInfo({required this.deviceId});

  @override
  int get hashCode => deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupDeviceInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId;
}

/// 本地备份文件条目（镜像 full_sync_backup::backup_repository::BackupEntry）
class BackupEntryView {
  final String filename;
  final String filePath;

  /// Unix 秒
  final PlatformInt64 modifiedAt;
  final PlatformInt64 sizeBytes;

  const BackupEntryView({
    required this.filename,
    required this.filePath,
    required this.modifiedAt,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      filename.hashCode ^
      filePath.hashCode ^
      modifiedAt.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupEntryView &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          filePath == other.filePath &&
          modifiedAt == other.modifiedAt &&
          sizeBytes == other.sizeBytes;
}

/// 导出结果（镜像 full_sync_backup_api::ExportResult）
class BackupExportResult {
  final String filePath;
  final PlatformInt64 fileSize;
  final List<BackupTableCount> tableCounts;
  final BackupManifestView manifest;

  /// 云端备份路径（仅上传成功时有值）
  final String? cloudPath;
  final bool cloudUploaded;

  /// 云端上传错误（上传失败时有值，不阻塞本地备份）
  final String? cloudError;

  /// 本地备份文件路径（写入成功时有值）
  final String? localPath;

  /// 本地写入错误（写入失败时有值）
  final String? localError;

  const BackupExportResult({
    required this.filePath,
    required this.fileSize,
    required this.tableCounts,
    required this.manifest,
    this.cloudPath,
    required this.cloudUploaded,
    this.cloudError,
    this.localPath,
    this.localError,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      fileSize.hashCode ^
      tableCounts.hashCode ^
      manifest.hashCode ^
      cloudPath.hashCode ^
      cloudUploaded.hashCode ^
      cloudError.hashCode ^
      localPath.hashCode ^
      localError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupExportResult &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          fileSize == other.fileSize &&
          tableCounts == other.tableCounts &&
          manifest == other.manifest &&
          cloudPath == other.cloudPath &&
          cloudUploaded == other.cloudUploaded &&
          cloudError == other.cloudError &&
          localPath == other.localPath &&
          localError == other.localError;
}

/// 导入结果（镜像 full_sync_backup_api::ImportResult）
class BackupImportResult {
  final PlatformInt64 successCount;
  final PlatformInt64 errorCount;
  final List<String> errors;
  final BackupManifestView manifest;
  final bool needsRestart;

  const BackupImportResult({
    required this.successCount,
    required this.errorCount,
    required this.errors,
    required this.manifest,
    required this.needsRestart,
  });

  @override
  int get hashCode =>
      successCount.hashCode ^
      errorCount.hashCode ^
      errors.hashCode ^
      manifest.hashCode ^
      needsRestart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupImportResult &&
          runtimeType == other.runtimeType &&
          successCount == other.successCount &&
          errorCount == other.errorCount &&
          errors == other.errors &&
          manifest == other.manifest &&
          needsRestart == other.needsRestart;
}

/// 备份清单（镜像 orbit_core::full_sync_backup::manifest::BackupManifest）
class BackupManifestView {
  final int formatVersion;

  /// RFC3339 字符串
  final String createdAt;
  final PlatformInt64 createdAtTs;
  final String appVersion;
  final String deviceId;
  final String? deviceName;
  final PlatformInt64 schemaVersion;
  final List<BackupTableCount> tableCounts;

  const BackupManifestView({
    required this.formatVersion,
    required this.createdAt,
    required this.createdAtTs,
    required this.appVersion,
    required this.deviceId,
    this.deviceName,
    required this.schemaVersion,
    required this.tableCounts,
  });

  @override
  int get hashCode =>
      formatVersion.hashCode ^
      createdAt.hashCode ^
      createdAtTs.hashCode ^
      appVersion.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      schemaVersion.hashCode ^
      tableCounts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupManifestView &&
          runtimeType == other.runtimeType &&
          formatVersion == other.formatVersion &&
          createdAt == other.createdAt &&
          createdAtTs == other.createdAtTs &&
          appVersion == other.appVersion &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          schemaVersion == other.schemaVersion &&
          tableCounts == other.tableCounts;
}

/// 备份偏好（镜像 full_sync_backup::backup_prefs::BackupPrefs；
/// schedule_type 用字符串承载以保持 Dart 侧可读）
class BackupPrefsView {
  final String? localPath;
  final bool keepLatest;
  final bool cloudBackupEnabled;
  final bool localBackupEnabled;

  /// off / hourly / daily / weekly / monthly / yearly
  final String scheduleType;

  /// "HH:mm"
  final String scheduleTime;
  final int scheduleMinute;
  final int scheduleWeekday;
  final int scheduleDayOfMonth;
  final int scheduleMonth;
  final PlatformInt64 lastBackupAt;
  final PlatformInt64 nextBackupAt;

  const BackupPrefsView({
    this.localPath,
    required this.keepLatest,
    required this.cloudBackupEnabled,
    required this.localBackupEnabled,
    required this.scheduleType,
    required this.scheduleTime,
    required this.scheduleMinute,
    required this.scheduleWeekday,
    required this.scheduleDayOfMonth,
    required this.scheduleMonth,
    required this.lastBackupAt,
    required this.nextBackupAt,
  });

  @override
  int get hashCode =>
      localPath.hashCode ^
      keepLatest.hashCode ^
      cloudBackupEnabled.hashCode ^
      localBackupEnabled.hashCode ^
      scheduleType.hashCode ^
      scheduleTime.hashCode ^
      scheduleMinute.hashCode ^
      scheduleWeekday.hashCode ^
      scheduleDayOfMonth.hashCode ^
      scheduleMonth.hashCode ^
      lastBackupAt.hashCode ^
      nextBackupAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupPrefsView &&
          runtimeType == other.runtimeType &&
          localPath == other.localPath &&
          keepLatest == other.keepLatest &&
          cloudBackupEnabled == other.cloudBackupEnabled &&
          localBackupEnabled == other.localBackupEnabled &&
          scheduleType == other.scheduleType &&
          scheduleTime == other.scheduleTime &&
          scheduleMinute == other.scheduleMinute &&
          scheduleWeekday == other.scheduleWeekday &&
          scheduleDayOfMonth == other.scheduleDayOfMonth &&
          scheduleMonth == other.scheduleMonth &&
          lastBackupAt == other.lastBackupAt &&
          nextBackupAt == other.nextBackupAt;
}

/// 备份内单条任务预览（镜像 full_sync_backup_api::PreviewTask）
class BackupPreviewTask {
  final String title;
  final String status;
  final bool done;
  final PlatformInt64? dueDate;
  final PlatformInt64 priority;

  /// 所属项目名（备份内解析不到为 None）
  final String? project;
  final bool isDeleted;

  const BackupPreviewTask({
    required this.title,
    required this.status,
    required this.done,
    this.dueDate,
    required this.priority,
    this.project,
    required this.isDeleted,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      status.hashCode ^
      done.hashCode ^
      dueDate.hashCode ^
      priority.hashCode ^
      project.hashCode ^
      isDeleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupPreviewTask &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          status == other.status &&
          done == other.done &&
          dueDate == other.dueDate &&
          priority == other.priority &&
          project == other.project &&
          isDeleted == other.isDeleted;
}

/// 恢复预览（镜像 full_sync_backup_api::BackupPreview）
class BackupPreviewView {
  final BackupManifestView manifest;
  final List<BackupPreviewTask> sampleTasks;
  final BackupTaskStats taskStats;

  /// 与当前库 schema 不一致（恢复需强制二次确认）
  final bool schemaMismatch;
  final PlatformInt64 currentSchemaVersion;

  const BackupPreviewView({
    required this.manifest,
    required this.sampleTasks,
    required this.taskStats,
    required this.schemaMismatch,
    required this.currentSchemaVersion,
  });

  @override
  int get hashCode =>
      manifest.hashCode ^
      sampleTasks.hashCode ^
      taskStats.hashCode ^
      schemaMismatch.hashCode ^
      currentSchemaVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupPreviewView &&
          runtimeType == other.runtimeType &&
          manifest == other.manifest &&
          sampleTasks == other.sampleTasks &&
          taskStats == other.taskStats &&
          schemaMismatch == other.schemaMismatch &&
          currentSchemaVersion == other.currentSchemaVersion;
}

/// 备份内单表记录数（BTreeMap 展开为有序列表，避免 FRB 对 Map 的镜像限制）
class BackupTableCount {
  final String table;
  final PlatformInt64 count;

  const BackupTableCount({required this.table, required this.count});

  @override
  int get hashCode => table.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupTableCount &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          count == other.count;
}

/// 备份内任务统计（镜像 full_sync_backup_api::TaskPreviewStats）
class BackupTaskStats {
  final PlatformInt64 total;
  final PlatformInt64 alive;
  final PlatformInt64 done;
  final PlatformInt64 deleted;

  const BackupTaskStats({
    required this.total,
    required this.alive,
    required this.done,
    required this.deleted,
  });

  @override
  int get hashCode =>
      total.hashCode ^ alive.hashCode ^ done.hashCode ^ deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupTaskStats &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          alive == other.alive &&
          done == other.done &&
          deleted == other.deleted;
}

/// 云端备份条目（Desktop CloudBackupEntryView 同口径）
class CloudBackupEntryView {
  final String name;

  /// 完整云端对象路径（peek / restore 回传用）
  final String cloudPath;
  final PlatformInt64 sizeBytes;
  final PlatformInt64 modifiedAt;

  const CloudBackupEntryView({
    required this.name,
    required this.cloudPath,
    required this.sizeBytes,
    required this.modifiedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      cloudPath.hashCode ^
      sizeBytes.hashCode ^
      modifiedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloudBackupEntryView &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cloudPath == other.cloudPath &&
          sizeBytes == other.sizeBytes &&
          modifiedAt == other.modifiedAt;
}
