// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`, `tick_once`

/// 启动节假日自动更新守护（幂等；Dart 在 DB 就绪后调用一次，BootGate 接线）
///
/// 每日固定时刻（默认 08:00 本地）一次；错过时刻后下次启动首轮 tick 即补更。
Future<void> startHolidayScheduler() =>
    RustLib.instance.api.crateApiHolidayStartHolidayScheduler();

/// 全部节假日（date 升序；空库回落预置 2026 表，冷启动可用）
Future<List<HolidayInfo>> holidayList() =>
    RustLib.instance.api.crateApiHolidayHolidayList();

/// 判定某日期：Some(true) 放假 / Some(false) 调休补班 / None 普通日
Future<bool?> holidayIsOn({required String date}) =>
    RustLib.instance.api.crateApiHolidayHolidayIsOn(date: date);

/// 手动更新（强制拉取；网络失败错误文案给 Dart toast，旧缓存保留）
Future<HolidayMeta> holidayUpdate() =>
    RustLib.instance.api.crateApiHolidayHolidayUpdate();

/// 更新记账（上次成功/尝试、连续失败次数、固定时刻）
Future<HolidayMeta> holidayMeta() =>
    RustLib.instance.api.crateApiHolidayHolidayMeta();

/// 设置每日固定更新时刻（0-23，越界 clamp）
Future<void> holidaySetFixedHour({required int hour}) =>
    RustLib.instance.api.crateApiHolidayHolidaySetFixedHour(hour: hour);
