// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 导出全部任务为 ICS（VTODO 日历；含完成态/优先级/截止映射）
Future<IcsExportView> icsExport() =>
    RustLib.instance.api.crateApiIcsExportIcsExport();

/// ICS 导出结果（FRB 镜像）
class IcsExportView {
  final String content;

  /// 各表行数（表名, 行数）有序对
  final List<IcsTableCount> tableCounts;

  /// 建议文件名（含时间戳）
  final String suggestedFilename;

  const IcsExportView({
    required this.content,
    required this.tableCounts,
    required this.suggestedFilename,
  });

  @override
  int get hashCode =>
      content.hashCode ^ tableCounts.hashCode ^ suggestedFilename.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcsExportView &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          tableCounts == other.tableCounts &&
          suggestedFilename == other.suggestedFilename;
}

/// 表行数统计项（独立类型名：FRB codegen 与 plaintext_export 的同名
/// TableCount 会混串生成物，独有名规避）
class IcsTableCount {
  final String table;
  final BigInt count;

  const IcsTableCount({required this.table, required this.count});

  @override
  int get hashCode => table.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcsTableCount &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          count == other.count;
}
