// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 一键数据库维护：WAL checkpoint → 附件 GC → 附件缓存上限 → 日志 TTL → PRAGMA optimize → VACUUM
Future<DbMaintenanceView> dbMaintenance() =>
    RustLib.instance.api.crateApiMaintenanceDbMaintenance();

/// 数据库维护结果视图（core DbMaintenanceResult 的本地 DTO 镜像——
/// FRB 不跨 crate 暴露 core 类型，保持两端壳独立演进自由度）
class DbMaintenanceView {
  /// WAL checkpoint 后 -wal 文件剩余大小（字节）
  final PlatformInt64 walBytesAfterCheckpoint;

  /// 附件 GC 清理的孤立文件数
  final int attachmentsCleaned;

  /// 日志 TTL 清理的行数（通知历史 + 活动日志，30 天口径）
  final int logRowsPruned;

  /// VACUUM 前空闲页数（碎片页）
  final PlatformInt64 freelistBefore;

  /// VACUUM 后空闲页数（应为 0）
  final PlatformInt64 freelistAfter;

  /// VACUUM 实际回收的页数
  final PlatformInt64 pagesReclaimed;

  const DbMaintenanceView({
    required this.walBytesAfterCheckpoint,
    required this.attachmentsCleaned,
    required this.logRowsPruned,
    required this.freelistBefore,
    required this.freelistAfter,
    required this.pagesReclaimed,
  });

  @override
  int get hashCode =>
      walBytesAfterCheckpoint.hashCode ^
      attachmentsCleaned.hashCode ^
      logRowsPruned.hashCode ^
      freelistBefore.hashCode ^
      freelistAfter.hashCode ^
      pagesReclaimed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbMaintenanceView &&
          runtimeType == other.runtimeType &&
          walBytesAfterCheckpoint == other.walBytesAfterCheckpoint &&
          attachmentsCleaned == other.attachmentsCleaned &&
          logRowsPruned == other.logRowsPruned &&
          freelistBefore == other.freelistBefore &&
          freelistAfter == other.freelistAfter &&
          pagesReclaimed == other.pagesReclaimed;
}
