// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 查询通知历史（created_at 倒序；kind 可选过滤；limit 默认 50 上限 200）
Future<List<NotificationLogRow>> notificationLogList({
  String? kind,
  PlatformInt64? limit,
}) => RustLib.instance.api.crateApiNotificationLogNotificationLogList(
  kind: kind,
  limit: limit,
);

/// 清空通知历史，返回删除行数
Future<BigInt> notificationLogClear() =>
    RustLib.instance.api.crateApiNotificationLogNotificationLogClear();

/// 通知历史行（镜像 orbit_core::api::notification_log_api::NotificationLogRow）
class NotificationLogRow {
  final PlatformInt64 id;

  /// reminder_due / snooze / complete / boot_skip
  final String kind;
  final PlatformInt64? taskId;

  /// 任务标题快照（任务后续被删仍可读）
  final String taskTitle;
  final PlatformInt64? reminderId;

  /// 附加 JSON：{remind_at, snooze_until, source}
  final String payload;

  /// 毫秒时间戳
  final PlatformInt64 createdAt;

  const NotificationLogRow({
    required this.id,
    required this.kind,
    this.taskId,
    required this.taskTitle,
    this.reminderId,
    required this.payload,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      taskId.hashCode ^
      taskTitle.hashCode ^
      reminderId.hashCode ^
      payload.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationLogRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          taskId == other.taskId &&
          taskTitle == other.taskTitle &&
          reminderId == other.reminderId &&
          payload == other.payload &&
          createdAt == other.createdAt;
}
