// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 导出全部待办数据为结构化 JSON（默认排除墓碑行）
Future<PlaintextExportView> plaintextExportJson({bool? excludeDeleted}) =>
    RustLib.instance.api.crateApiPlaintextExportPlaintextExportJson(
      excludeDeleted: excludeDeleted,
    );

/// 导出任务主视图 CSV（UTF-8 with BOM；默认排除墓碑行）
Future<PlaintextExportView> plaintextExportCsv({bool? excludeDeleted}) =>
    RustLib.instance.api.crateApiPlaintextExportPlaintextExportCsv(
      excludeDeleted: excludeDeleted,
    );

/// 明文导出结果（FRB 镜像）
class PlaintextExportView {
  /// 文件内容（JSON 文本或 CSV 文本，UTF-8；CSV 带 BOM）
  final String content;

  /// 各表行数（表名, 行数）有序对
  final List<TableCount> tableCounts;

  /// 建议文件名（含时间戳）
  final String suggestedFilename;

  const PlaintextExportView({
    required this.content,
    required this.tableCounts,
    required this.suggestedFilename,
  });

  @override
  int get hashCode =>
      content.hashCode ^ tableCounts.hashCode ^ suggestedFilename.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaintextExportView &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          tableCounts == other.tableCounts &&
          suggestedFilename == other.suggestedFilename;
}

/// 表行数统计项
class TableCount {
  final String table;
  final BigInt count;

  const TableCount({required this.table, required this.count});

  @override
  int get hashCode => table.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableCount &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          count == other.count;
}
