// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 列出全部保存的筛选器
Future<List<TodoSavedFilter>> savedFiltersList() =>
    RustLib.instance.api.crateApiSavedFilterSavedFiltersList();

/// 创建保存的筛选器
Future<TodoSavedFilter> savedFilterCreate({
  required TodoSavedFilterCreateInput input,
}) => RustLib.instance.api.crateApiSavedFilterSavedFilterCreate(input: input);

/// 更新保存的筛选器
Future<TodoSavedFilter> savedFilterUpdate({
  required PlatformInt64 id,
  required TodoSavedFilterUpdateInput input,
}) => RustLib.instance.api.crateApiSavedFilterSavedFilterUpdate(
  id: id,
  input: input,
);

/// 删除保存的筛选器（软删）
Future<void> savedFilterDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiSavedFilterSavedFilterDelete(id: id);
