// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 全局搜索（任务/项目/评论三路 LIKE；空关键词返回空结果；limit ≤0 → 20）
Future<GlobalSearchResult> globalSearch({
  required String keyword,
  int? limit,
}) => RustLib.instance.api.crateApiSearchGlobalSearch(
  keyword: keyword,
  limit: limit,
);

/// 评论命中行（镜像 core CommentSearchHit）
class CommentSearchHit {
  final PlatformInt64 commentId;
  final PlatformInt64 taskId;
  final String taskTitle;
  final String content;
  final PlatformInt64 createdAt;

  const CommentSearchHit({
    required this.commentId,
    required this.taskId,
    required this.taskTitle,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      commentId.hashCode ^
      taskId.hashCode ^
      taskTitle.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentSearchHit &&
          runtimeType == other.runtimeType &&
          commentId == other.commentId &&
          taskId == other.taskId &&
          taskTitle == other.taskTitle &&
          content == other.content &&
          createdAt == other.createdAt;
}

/// 三路聚合结果（镜像 core GlobalSearchResult）
class GlobalSearchResult {
  final List<TodoTask> tasks;
  final List<TodoProject> projects;
  final List<CommentSearchHit> comments;

  const GlobalSearchResult({
    required this.tasks,
    required this.projects,
    required this.comments,
  });

  static Future<GlobalSearchResult> default_() =>
      RustLib.instance.api.crateApiSearchGlobalSearchResultDefault();

  @override
  int get hashCode => tasks.hashCode ^ projects.hashCode ^ comments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalSearchResult &&
          runtimeType == other.runtimeType &&
          tasks == other.tasks &&
          projects == other.projects &&
          comments == other.comments;
}
