// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 统计聚合（year 为热力图年份；None = 当前年滚动 365 天窗口）
Future<StatsAggregate> statsAggregate({PlatformInt64? year}) =>
    RustLib.instance.api.crateApiStatsStatsAggregate(year: year);

/// 一次性聚合结果（镜像 core StatsAggregate）
class StatsAggregate {
  final StatsOverview overview;
  final StatsHeatmap heatmap;
  final StatsStreak streak;
  final List<StatsProjectRow> byProject;
  final List<StatsPriorityRow> byPriority;
  final List<StatsWeekdayRow> byWeekday;

  /// 热力图可选年份（升序；有完成记录的年份，空则 [当前年]）
  final Int64List availableYears;

  const StatsAggregate({
    required this.overview,
    required this.heatmap,
    required this.streak,
    required this.byProject,
    required this.byPriority,
    required this.byWeekday,
    required this.availableYears,
  });

  @override
  int get hashCode =>
      overview.hashCode ^
      heatmap.hashCode ^
      streak.hashCode ^
      byProject.hashCode ^
      byPriority.hashCode ^
      byWeekday.hashCode ^
      availableYears.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsAggregate &&
          runtimeType == other.runtimeType &&
          overview == other.overview &&
          heatmap == other.heatmap &&
          streak == other.streak &&
          byProject == other.byProject &&
          byPriority == other.byPriority &&
          byWeekday == other.byWeekday &&
          availableYears == other.availableYears;
}

/// 热力图数据（镜像 core HeatmapData；year 回显 + 按年窗口）
class StatsHeatmap {
  final PlatformInt64 year;
  final String startDate;
  final String endDate;
  final List<StatsHeatmapCell> cells;

  const StatsHeatmap({
    required this.year,
    required this.startDate,
    required this.endDate,
    required this.cells,
  });

  @override
  int get hashCode =>
      year.hashCode ^ startDate.hashCode ^ endDate.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsHeatmap &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          cells == other.cells;
}

/// 热力图单格（镜像 core HeatmapCell）
class StatsHeatmapCell {
  final String date;
  final PlatformInt64 count;

  const StatsHeatmapCell({required this.date, required this.count});

  @override
  int get hashCode => date.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsHeatmapCell &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          count == other.count;
}

/// 总览卡（镜像 core StatsOverview）
class StatsOverview {
  final PlatformInt64 total;
  final PlatformInt64 pending;
  final PlatformInt64 done;
  final PlatformInt64 doneLast7D;
  final PlatformInt64 doneLast30D;

  const StatsOverview({
    required this.total,
    required this.pending,
    required this.done,
    required this.doneLast7D,
    required this.doneLast30D,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      pending.hashCode ^
      done.hashCode ^
      doneLast7D.hashCode ^
      doneLast30D.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsOverview &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          pending == other.pending &&
          done == other.done &&
          doneLast7D == other.doneLast7D &&
          doneLast30D == other.doneLast30D;
}

/// 优先级分布行（镜像 core PriorityDistRow）
class StatsPriorityRow {
  final PlatformInt64 priority;
  final PlatformInt64 doneCount;
  final PlatformInt64 pendingCount;

  const StatsPriorityRow({
    required this.priority,
    required this.doneCount,
    required this.pendingCount,
  });

  @override
  int get hashCode =>
      priority.hashCode ^ doneCount.hashCode ^ pendingCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsPriorityRow &&
          runtimeType == other.runtimeType &&
          priority == other.priority &&
          doneCount == other.doneCount &&
          pendingCount == other.pendingCount;
}

/// 项目分布行（镜像 core ProjectDistRow；title None = 未分组）
class StatsProjectRow {
  final PlatformInt64? projectId;
  final String? projectTitle;
  final String? projectHexColor;
  final PlatformInt64 doneCount;
  final PlatformInt64 pendingCount;

  const StatsProjectRow({
    this.projectId,
    this.projectTitle,
    this.projectHexColor,
    required this.doneCount,
    required this.pendingCount,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectTitle.hashCode ^
      projectHexColor.hashCode ^
      doneCount.hashCode ^
      pendingCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsProjectRow &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectTitle == other.projectTitle &&
          projectHexColor == other.projectHexColor &&
          doneCount == other.doneCount &&
          pendingCount == other.pendingCount;
}

/// 连续完成天数（镜像 core StreakData）
class StatsStreak {
  final PlatformInt64 current;
  final PlatformInt64 best;
  final bool doneToday;

  const StatsStreak({
    required this.current,
    required this.best,
    required this.doneToday,
  });

  @override
  int get hashCode => current.hashCode ^ best.hashCode ^ doneToday.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsStreak &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          best == other.best &&
          doneToday == other.doneToday;
}

/// 星期分布行（镜像 core WeekdayDistRow；0=周一 … 6=周日）
class StatsWeekdayRow {
  final PlatformInt64 weekday;
  final PlatformInt64 doneCount;

  const StatsWeekdayRow({required this.weekday, required this.doneCount});

  @override
  int get hashCode => weekday.hashCode ^ doneCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsWeekdayRow &&
          runtimeType == other.runtimeType &&
          weekday == other.weekday &&
          doneCount == other.doneCount;
}
