// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_state`, `new`, `set_state`, `with_state_mut`, `with_state_pool`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OrbitState`

/// 查询桥接状态是否已初始化（诊断用）
Future<bool> orbitStateInitialized() =>
    RustLib.instance.api.crateApiStateOrbitStateInitialized();
