// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 列出冲突记录（`resolution` 为 None 时返回全部；按时间倒序分页）
Future<List<SyncConflict>> syncConflictList({
  String? resolution,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiSyncConflictSyncConflictList(
  resolution: resolution,
  limit: limit,
  offset: offset,
);

/// 统计冲突记录数（传 "unresolved" 只要待处理）
Future<PlatformInt64> syncConflictCount({String? resolution}) => RustLib
    .instance
    .api
    .crateApiSyncConflictSyncConflictCount(resolution: resolution);

/// 恢复某条冲突的败方内容（返回被写回的原行 id）
Future<PlatformInt64> syncConflictRestore({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiSyncConflictSyncConflictRestore(id: id);

/// 忽略某条冲突（不改业务数据）
Future<void> syncConflictDismiss({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiSyncConflictSyncConflictDismiss(id: id);

/// 清空冲突记录（`resolution` 为 None 时清全部），返回删除条数
Future<PlatformInt64> syncConflictClear({String? resolution}) => RustLib
    .instance
    .api
    .crateApiSyncConflictSyncConflictClear(resolution: resolution);
