// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_config`, `attach_password_to_runtime`, `attachments_dir`, `auto_sync_flag`, `base_path_normalized`, `bucket_trimmed`, `detach_password_from_runtime`, `engine_config_of_record`, `err_tagged_cloud`, `err_tagged_crypto`, `from_record`, `interval_clamped`, `parse_origin`, `password_str`, `region_trimmed`, `run_sync`, `runtime_crypto`, `runtime_engine`, `skip_tls_flag`, `sync_on_change_flag`, `timeout_clamped`, `username_str`, `with_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SyncAction`, `SyncRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 读取当前激活配置（未配置返回 null）
///
/// 对齐桌面 `sync_config_get`。
Future<SyncConfigView?> syncConfigGet() =>
    RustLib.instance.api.crateApiSyncSyncConfigGet();

/// 保存同步配置（DB 单写；激活互斥由仓储层保证）
///
/// 对齐桌面 `sync_config_save`。差异：
/// - 加密文件侧写（write_config_file）跳过：移动端未注册全局
///   EncryptedConfigStorage，DB 为唯一事实源（keyring 降级策略见模块注释）；
/// - emit("sync-config-changed") 不广播，Dart 保存成功后自行刷新状态。
Future<SyncConfigView> syncConfigSave({required SyncConfigInput input}) =>
    RustLib.instance.api.crateApiSyncSyncConfigSave(input: input);

/// 测试连接（不落盘）：validate → 构造适配器 → list 探测
///
/// 对齐桌面 `sync_test_connection`。用户名/密码留空且已有激活配置时沿用已存
/// 凭据（同协议才回填）；返回云端根目录发现的条目数，网络错误统一 `[network]` 前缀。
Future<int> syncTestConnection({required SyncConfigInput input}) =>
    RustLib.instance.api.crateApiSyncSyncTestConnection(input: input);

/// 完整同步（Pull → Push + 附件）——「立即同步」唯一入口；忙时返回 skipped 结果
///
/// 对齐桌面 `cloud_sync_now`；返回 SyncResult 的 JSON 字符串。
Future<String> cloudSyncNow({required String origin}) =>
    RustLib.instance.api.crateApiSyncCloudSyncNow(origin: origin);

/// 仅 Push（修改后立即同步场景预留）
///
/// 对齐桌面 `cloud_sync_push_only`。
Future<String> cloudSyncPushOnly({required String origin}) =>
    RustLib.instance.api.crateApiSyncCloudSyncPushOnly(origin: origin);

/// 先 Pull 再 Push（启动场景预留）
///
/// 对齐桌面 `cloud_sync_pull_then_push`。
Future<String> cloudSyncPullThenPush({required String origin}) =>
    RustLib.instance.api.crateApiSyncCloudSyncPullThenPush(origin: origin);

/// 强制同步（进入 / 退出应用专用，对齐桌面 `cloud_sync_force`）
///
/// 与 `cloud_sync_now` 的差别只在前提判定：不检查自动同步开关/间隔，
/// 是否该同步由调用方（生命周期钩子）判定。引擎忙时最多等待
/// `wait_for_idle_ms` 毫秒再执行；返回 SyncResult 的 JSON 字符串。
Future<String> cloudSyncForce({
  required String origin,
  required BigInt waitForIdleMs,
}) => RustLib.instance.api.crateApiSyncCloudSyncForce(
  origin: origin,
  waitForIdleMs: waitForIdleMs,
);

/// 本地同步状态账本（sync_state.json；指纹元数据，不含业务数据）
///
/// 对齐桌面 `cloud_sync_get_state`；返回 SyncState 的 JSON 字符串。
Future<String> cloudSyncGetState() =>
    RustLib.instance.api.crateApiSyncCloudSyncGetState();

/// 是否有同步任务正在运行
///
/// 对齐桌面 `cloud_sync_is_running`。
Future<bool> cloudSyncIsRunning() =>
    RustLib.instance.api.crateApiSyncCloudSyncIsRunning();

/// 查询增量同步历史（P1-17 展示面；设置页「同步历史」卡数据源）
///
/// `scope`：all | incremental | push_only | pull_only（口径见 core API 文档）；
/// 只读聚合不 emit 事件；limit 由前端夹紧（1..=200）。
///
/// 对齐桌面 `cloud_sync_history`。
Future<List<SyncHistoryView>> cloudSyncHistory({
  required String scope,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiSyncCloudSyncHistory(
  scope: scope,
  limit: limit,
);

/// 断开云同步：软删激活配置 + 清空本地指纹账本（下次配置后触发全量重推）
///
/// 对齐桌面 `sync_disconnect`。不删除云端数据与本地 crypto meta
/// （Data Key 保留，重新接入同一路径可续用）。
/// 差异：emit("sync-config-changed") 不广播，Dart 调用成功后自行刷新。
Future<void> syncDisconnect() =>
    RustLib.instance.api.crateApiSyncSyncDisconnect();

/// 同步加密状态查询（设置页状态卡数据源）
///
/// 对齐桌面 `sync_crypto_status`。
Future<SyncCryptoStatus> syncCryptoStatus() =>
    RustLib.instance.api.crateApiSyncSyncCryptoStatus();

/// 本机密钥方案版本（"v1" | "v2"；未设置密码返回 null）
///
/// 对齐桌面 `sync_crypto_meta_version`；设置页/恢复页据此显示 v1→v2 迁移入口。
Future<String?> syncCryptoMetaVersion() =>
    RustLib.instance.api.crateApiSyncSyncCryptoMetaVersion();

/// v1 → v2 密钥方案迁移（同密码确定性派生 + 云端全量重传；UI 二次确认后调用）
///
/// 对齐桌面 `sync_crypto_upgrade_v2`。迁移后所有设备输入同一密码即可同步。
Future<void> syncCryptoUpgradeV2({required String syncPassword}) => RustLib
    .instance
    .api
    .crateApiSyncSyncCryptoUpgradeV2(syncPassword: syncPassword);

/// rekey 全量重传：用当前 Data Key 重加密覆盖云端（恢复「以本机为准」）
///
/// 对齐桌面 `cloud_sync_rekey`。危险操作，UI 必须二次确认后调用。
Future<String> cloudSyncRekey() =>
    RustLib.instance.api.crateApiSyncCloudSyncRekey();

/// 首次设置同步密码（生成 Data Key 并持久化 meta；成功即解锁）
///
/// 对齐桌面 `sync_crypto_init`。`remember` 仅保留参数面对齐：移动端无系统
/// 凭据库，缓存退化为进程内会话缓存，重启后需重输。
Future<void> syncCryptoInit({
  required String password,
  required bool remember,
}) => RustLib.instance.api.crateApiSyncSyncCryptoInit(
  password: password,
  remember: remember,
);

/// 解锁同步加密（验证密码并将 Data Key 载入内存）
///
/// 对齐桌面 `sync_crypto_unlock`；remember 语义同 [sync_crypto_init]。
Future<void> syncCryptoUnlock({
  required String password,
  required bool remember,
}) => RustLib.instance.api.crateApiSyncSyncCryptoUnlock(
  password: password,
  remember: remember,
);

/// 锁定同步加密（清除内存 Data Key 与会话密码缓存）
///
/// 对齐桌面 `sync_crypto_lock`。差异：无钥匙串缓存可保留，会话内一并清除。
Future<void> syncCryptoLock() =>
    RustLib.instance.api.crateApiSyncSyncCryptoLock();

/// 修改同步密码
///
/// 对齐桌面 `sync_crypto_change_password`。v2 密钥方案下改密即换 Key，
/// 命令内部编排云端全量重传（rekey），失败回滚本机密码；无激活云同步配置时
/// v2 改密报错（重传无处执行）。
Future<void> syncCryptoChangePassword({
  required String oldPassword,
  required String newPassword,
}) => RustLib.instance.api.crateApiSyncSyncCryptoChangePassword(
  oldPassword: oldPassword,
  newPassword: newPassword,
);

/// 导出 crypto bundle（跨设备 Data Key 分发的本地侧载体）
///
/// 对齐桌面 `sync_crypto_export_bundle`；返回 SyncCryptoMeta 的 JSON 字符串
/// （避免跨 crate 结构体直接过 FRB），Dart 侧透传给 [sync_crypto_import_bundle]。
Future<String> syncCryptoExportBundle() =>
    RustLib.instance.api.crateApiSyncSyncCryptoExportBundle();

/// 导入手动提供的 crypto bundle（JSON 字符串，字段同 core SyncCryptoMeta）
///
/// 对齐桌面 `sync_crypto_import_bundle`。返回 data_key 的 base64；
/// `[local_meta_exists]` 前缀表示 Fix-10 守卫拒绝，前端确认后以 force=true 重试。
Future<String> syncCryptoImportBundle({
  required String bundleJson,
  required String password,
  required bool force,
}) => RustLib.instance.api.crateApiSyncSyncCryptoImportBundle(
  bundleJson: bundleJson,
  password: password,
  force: force,
);

/// 启动静默恢复会话：尝试用缓存的同步密码解锁
///
/// 对齐桌面 `sync_crypto_restore_session`。移动端 keyring 降级：无跨重启的
/// 持久缓存（会话密码随 lock 一并清除），故除「本就已解锁」外恒返回 false，
/// Dart 侧引导用户手动输入。
Future<bool> syncCryptoRestoreSession() =>
    RustLib.instance.api.crateApiSyncSyncCryptoRestoreSession();

/// 忘记本机同步密码：清除会话缓存与引擎挂载（对齐桌面 `sync_crypto_forget_session`；
/// 桌面另清钥匙串，移动端无持久缓存可清）
Future<void> syncCryptoForgetSession() =>
    RustLib.instance.api.crateApiSyncSyncCryptoForgetSession();

/// 前端提交的同步配置输入（镜像桌面 sync_cmd::SyncConfigInput）
///
/// 桌面用 serde(default) 补默认值；FRB 参数面改为 Option 字段，
/// 由 [sync_config_save]/[sync_test_connection] 按桌面默认值展开。
class SyncConfigInput {
  /// "webdav" | "s3"
  final String engine;

  /// WebDAV 服务器 URL / S3 endpoint
  final String endpoint;

  /// S3 bucket（WebDAV 留空/null）
  final String? bucket;

  /// S3 region（WebDAV 留空/null）
  final String? region;

  /// WebDAV 用户名 / S3 access_key_id
  final String? username;

  /// WebDAV 密码 / S3 secret_access_key（留空/null 表示沿用已存凭据）
  final String? password;

  /// 云端根路径（null 时默认 "orbit"）
  final String? basePath;

  /// 定时同步间隔分钟；0 = 关闭定时
  final PlatformInt64? intervalMinutes;

  /// 总开关（自动同步）；null 时默认 true
  final bool? autoSyncEnabled;

  /// 修改后立即同步（调度在壳层：桌面 `sync_scheduler.rs` / 移动
  /// `services/sync_on_change_scheduler.dart`；本层仅存取配置）
  final bool? syncOnChange;

  /// 跳过 TLS 证书校验（自签名证书）
  final bool? skipTlsVerify;

  /// 请求超时秒数；0 = 默认 30
  final PlatformInt64? timeoutSeconds;

  const SyncConfigInput({
    required this.engine,
    required this.endpoint,
    this.bucket,
    this.region,
    this.username,
    this.password,
    this.basePath,
    this.intervalMinutes,
    this.autoSyncEnabled,
    this.syncOnChange,
    this.skipTlsVerify,
    this.timeoutSeconds,
  });

  @override
  int get hashCode =>
      engine.hashCode ^
      endpoint.hashCode ^
      bucket.hashCode ^
      region.hashCode ^
      username.hashCode ^
      password.hashCode ^
      basePath.hashCode ^
      intervalMinutes.hashCode ^
      autoSyncEnabled.hashCode ^
      syncOnChange.hashCode ^
      skipTlsVerify.hashCode ^
      timeoutSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConfigInput &&
          runtimeType == other.runtimeType &&
          engine == other.engine &&
          endpoint == other.endpoint &&
          bucket == other.bucket &&
          region == other.region &&
          username == other.username &&
          password == other.password &&
          basePath == other.basePath &&
          intervalMinutes == other.intervalMinutes &&
          autoSyncEnabled == other.autoSyncEnabled &&
          syncOnChange == other.syncOnChange &&
          skipTlsVerify == other.skipTlsVerify &&
          timeoutSeconds == other.timeoutSeconds;
}

/// 前端展示用配置视图（凭据打码返回；镜像桌面 sync_cmd::SyncConfigView）
class SyncConfigView {
  final PlatformInt64 id;
  final String engine;
  final String endpoint;
  final String bucket;
  final String region;
  final String username;

  /// 打码：仅提示已设置
  final bool passwordSet;
  final String basePath;
  final PlatformInt64 intervalMinutes;
  final bool autoSyncEnabled;
  final bool syncOnChange;
  final bool skipTlsVerify;
  final PlatformInt64 timeoutSeconds;
  final PlatformInt64? lastSyncedAt;

  const SyncConfigView({
    required this.id,
    required this.engine,
    required this.endpoint,
    required this.bucket,
    required this.region,
    required this.username,
    required this.passwordSet,
    required this.basePath,
    required this.intervalMinutes,
    required this.autoSyncEnabled,
    required this.syncOnChange,
    required this.skipTlsVerify,
    required this.timeoutSeconds,
    this.lastSyncedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      engine.hashCode ^
      endpoint.hashCode ^
      bucket.hashCode ^
      region.hashCode ^
      username.hashCode ^
      passwordSet.hashCode ^
      basePath.hashCode ^
      intervalMinutes.hashCode ^
      autoSyncEnabled.hashCode ^
      syncOnChange.hashCode ^
      skipTlsVerify.hashCode ^
      timeoutSeconds.hashCode ^
      lastSyncedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConfigView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          engine == other.engine &&
          endpoint == other.endpoint &&
          bucket == other.bucket &&
          region == other.region &&
          username == other.username &&
          passwordSet == other.passwordSet &&
          basePath == other.basePath &&
          intervalMinutes == other.intervalMinutes &&
          autoSyncEnabled == other.autoSyncEnabled &&
          syncOnChange == other.syncOnChange &&
          skipTlsVerify == other.skipTlsVerify &&
          timeoutSeconds == other.timeoutSeconds &&
          lastSyncedAt == other.lastSyncedAt;
}

/// 同步加密状态查询载荷（镜像桌面 sync_crypto_cmd::SyncCryptoStatus）
class SyncCryptoStatus {
  final bool hasPassword;
  final bool isUnlocked;

  const SyncCryptoStatus({required this.hasPassword, required this.isUnlocked});

  @override
  int get hashCode => hasPassword.hashCode ^ isUnlocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncCryptoStatus &&
          runtimeType == other.runtimeType &&
          hasPassword == other.hasPassword &&
          isUnlocked == other.isUnlocked;
}

/// 增量同步历史行（镜像 orbit_core::models::business::SyncHistory）
///
/// 只读聚合（sync_history 表），不 emit 事件、不进同步白名单。
class SyncHistoryView {
  final PlatformInt64 id;

  /// sync_now / push_only / pull_then_push
  final String syncType;

  /// success / failed / conflict 等
  final String status;
  final PlatformInt64 startedAt;
  final PlatformInt64? finishedAt;
  final PlatformInt64 pulledCount;
  final PlatformInt64 pushedCount;
  final PlatformInt64 conflictCount;
  final String? errorMessage;

  const SyncHistoryView({
    required this.id,
    required this.syncType,
    required this.status,
    required this.startedAt,
    this.finishedAt,
    required this.pulledCount,
    required this.pushedCount,
    required this.conflictCount,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      syncType.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      finishedAt.hashCode ^
      pulledCount.hashCode ^
      pushedCount.hashCode ^
      conflictCount.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncHistoryView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          syncType == other.syncType &&
          status == other.status &&
          startedAt == other.startedAt &&
          finishedAt == other.finishedAt &&
          pulledCount == other.pulledCount &&
          pushedCount == other.pushedCount &&
          conflictCount == other.conflictCount &&
          errorMessage == other.errorMessage;
}
