// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 列出全部任务模板
Future<List<TodoTemplate>> templatesList() =>
    RustLib.instance.api.crateApiTemplateTemplatesList();

/// 创建任务模板
Future<TodoTemplate> templateCreate({required TodoTemplateCreateInput input}) =>
    RustLib.instance.api.crateApiTemplateTemplateCreate(input: input);

/// 更新任务模板
Future<TodoTemplate> templateUpdate({
  required PlatformInt64 id,
  required TodoTemplateUpdateInput input,
}) => RustLib.instance.api.crateApiTemplateTemplateUpdate(id: id, input: input);

/// 删除任务模板（软删）
Future<void> templateDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTemplateTemplateDelete(id: id);
