// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 列出项目（对应桌面 todo_projects_list）
Future<List<TodoProject>> todoProjectsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsList(filter: filter);

/// 获取单个项目（对应桌面 todo_projects_get）
Future<TodoProject> todoProjectsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsGet(id: id);

/// 创建项目（对应桌面 todo_projects_create）
Future<TodoProject> todoProjectsCreate({
  required TodoProjectCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoProjectsCreate(input: input);

/// 更新项目（对应桌面 todo_projects_update；patch 三态语义见模块文档）
Future<TodoProject> todoProjectsUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoProjectsUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除项目（软删，对应桌面 todo_projects_delete）
Future<void> todoProjectsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsDelete(id: id);

/// 更新项目排序位置（拖拽排序，对应桌面 todo_cmd::todo_projects_update_sort_order）
Future<void> todoProjectsUpdateSortOrder({
  required PlatformInt64 id,
  required double sortOrder,
}) => RustLib.instance.api.crateApiTodoTodoProjectsUpdateSortOrder(
  id: id,
  sortOrder: sortOrder,
);

/// 列出任务（对应桌面 todo_tasks_list）
Future<List<TodoTask>> todoTasksList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoTasksList(filter: filter);

/// 获取单个任务（对应桌面 todo_tasks_get）
Future<TodoTask> todoTasksGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksGet(id: id);

/// 创建任务（对应桌面 todo_tasks_create）
Future<TodoTask> todoTasksCreate({required TodoTaskCreateInput input}) =>
    RustLib.instance.api.crateApiTodoTodoTasksCreate(input: input);

/// 更新任务（对应桌面 todo_tasks_update；patch 三态语义见模块文档，
/// 如 project_id: null 表示移出项目，而缺省键表示不改归属）
Future<TodoTask> todoTasksUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoTasksUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除任务（软删，对应桌面 todo_tasks_delete）
Future<void> todoTasksDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksDelete(id: id);

/// 更新任务排序位置（拖拽排序，对应桌面 todo_cmd::todo_tasks_update_position）
Future<void> todoTasksUpdatePosition({
  required PlatformInt64 id,
  required double position,
}) => RustLib.instance.api.crateApiTodoTodoTasksUpdatePosition(
  id: id,
  position: position,
);

/// 任务详情聚合（含子任务/标签/评论/关系/提醒，对应桌面 todo_cmd::todo_tasks_get_detail）
Future<TodoTaskDetail> todoTasksGetDetail({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksGetDetail(id: id);

/// 列出子任务（对应桌面 todo_subtasks_list）
Future<List<TodoSubtask>> todoSubtasksList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksList(filter: filter);

/// 获取单个子任务（对应桌面 todo_subtasks_get）
Future<TodoSubtask> todoSubtasksGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksGet(id: id);

/// 创建子任务（对应桌面 todo_subtasks_create）
Future<TodoSubtask> todoSubtasksCreate({
  required TodoSubtaskCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoSubtasksCreate(input: input);

/// 更新子任务（对应桌面 todo_subtasks_update；patch 三态语义见模块文档）
Future<TodoSubtask> todoSubtasksUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoSubtasksUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除子任务（软删，对应桌面 todo_subtasks_delete）
Future<void> todoSubtasksDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksDelete(id: id);

/// 切换子任务完成状态（对应桌面 todo_cmd::todo_subtasks_toggle_done；
/// core 内部自动重算父任务 percent_done）
Future<void> todoSubtasksToggleDone({
  required PlatformInt64 subtaskId,
  required bool done,
}) => RustLib.instance.api.crateApiTodoTodoSubtasksToggleDone(
  subtaskId: subtaskId,
  done: done,
);

/// 列出标签（对应桌面 todo_labels_list）
Future<List<TodoLabel>> todoLabelsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsList(filter: filter);

/// 创建标签（对应桌面 todo_labels_create）
Future<TodoLabel> todoLabelsCreate({required TodoLabelCreateInput input}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsCreate(input: input);

/// 更新标签（对应桌面 todo_labels_update；patch 三态语义见模块文档）
Future<TodoLabel> todoLabelsUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoLabelsUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除标签（软删，对应桌面 todo_labels_delete）
Future<void> todoLabelsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsDelete(id: id);

/// 列出任务↔标签关联（对应桌面 todo_task_labels_list）
Future<List<TodoTaskLabel>> todoTaskLabelsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoTaskLabelsList(filter: filter);

/// 关联标签到任务（对应桌面 todo_task_labels_create）
Future<TodoTaskLabel> todoTaskLabelsCreate({
  required TodoTaskLabelCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoTaskLabelsCreate(input: input);

/// 解除关联（软删，对应桌面 todo_task_labels_delete）
Future<void> todoTaskLabelsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskLabelsDelete(id: id);

/// 列出评论（对应桌面 todo_comments_list）
Future<List<TodoComment>> todoCommentsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoCommentsList(filter: filter);

/// 获取单条评论（对应桌面 todo_comments_get）
Future<TodoComment> todoCommentsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoCommentsGet(id: id);

/// 创建评论（对应桌面 todo_comments_create）
Future<TodoComment> todoCommentsCreate({
  required TodoCommentCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoCommentsCreate(input: input);

/// 删除评论（软删，对应桌面 todo_comments_delete）
Future<void> todoCommentsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoCommentsDelete(id: id);

/// 列出任务关系（对应桌面 todo_task_relations_list）
Future<List<TodoTaskRelation>> todoTaskRelationsList({
  required ListFilter filter,
}) => RustLib.instance.api.crateApiTodoTodoTaskRelationsList(filter: filter);

/// 获取单条关系（对应桌面 todo_task_relations_get）
Future<TodoTaskRelation> todoTaskRelationsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskRelationsGet(id: id);

/// 创建任务关系（对应桌面 todo_task_relations_create）
Future<TodoTaskRelation> todoTaskRelationsCreate({
  required TodoTaskRelationCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoTaskRelationsCreate(input: input);

/// 删除任务关系（软删，对应桌面 todo_task_relations_delete）
Future<void> todoTaskRelationsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskRelationsDelete(id: id);

/// 列出提醒（对应桌面 todo_reminders_list）
Future<List<TodoReminder>> todoRemindersList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoRemindersList(filter: filter);

/// 获取单条提醒（对应桌面 todo_reminders_get）
Future<TodoReminder> todoRemindersGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoRemindersGet(id: id);

/// 创建提醒（对应桌面 todo_reminders_create）
Future<TodoReminder> todoRemindersCreate({
  required TodoReminderCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoRemindersCreate(input: input);

/// 删除提醒（软删，对应桌面 todo_reminders_delete）
Future<void> todoRemindersDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoRemindersDelete(id: id);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ListFilter>>
abstract class ListFilter implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoComment>>
abstract class TodoComment implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoCommentCreateInput>>
abstract class TodoCommentCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoLabel>>
abstract class TodoLabel implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoLabelCreateInput>>
abstract class TodoLabelCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoProject>>
abstract class TodoProject implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoProjectCreateInput>>
abstract class TodoProjectCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoReminder>>
abstract class TodoReminder implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoReminderCreateInput>>
abstract class TodoReminderCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoSubtask>>
abstract class TodoSubtask implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoSubtaskCreateInput>>
abstract class TodoSubtaskCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoTask>>
abstract class TodoTask implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoTaskCreateInput>>
abstract class TodoTaskCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< TodoTaskDetail>>
abstract class TodoTaskDetail implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoTaskLabel>>
abstract class TodoTaskLabel implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoTaskLabelCreateInput>>
abstract class TodoTaskLabelCreateInput implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoTaskRelation>>
abstract class TodoTaskRelation implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TodoTaskRelationCreateInput>>
abstract class TodoTaskRelationCreateInput implements RustOpaqueInterface {}
