// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`

/// 列出项目（对应桌面 todo_projects_list；默认排除已归档项目）
Future<List<TodoProject>> todoProjectsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsList(filter: filter);

/// 归档项目列表（对应桌面 todo_projects_list_archived；侧栏归档区数据源。
/// 归档/取消归档走 todo_projects_update 的 patch_json {"is_archived":0|1}，
/// 无独立切换命令——与桌面 is_archived 谓词同口径）
Future<List<TodoProject>> todoProjectsListArchived() =>
    RustLib.instance.api.crateApiTodoTodoProjectsListArchived();

/// 获取单个项目（对应桌面 todo_projects_get）
Future<TodoProject> todoProjectsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsGet(id: id);

/// 创建项目（对应桌面 todo_projects_create）
Future<TodoProject> todoProjectsCreate({
  required TodoProjectCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoProjectsCreate(input: input);

/// 更新项目（对应桌面 todo_projects_update；patch 三态语义见模块文档）
Future<TodoProject> todoProjectsUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoProjectsUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除项目（软删，对应桌面 todo_projects_delete）
Future<void> todoProjectsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsDelete(id: id);

/// 更新项目排序位置（拖拽排序，对应桌面 todo_cmd::todo_projects_update_sort_order）
Future<void> todoProjectsUpdateSortOrder({
  required PlatformInt64 id,
  required double sortOrder,
}) => RustLib.instance.api.crateApiTodoTodoProjectsUpdateSortOrder(
  id: id,
  sortOrder: sortOrder,
);

/// 列出任务（对应桌面 todo_tasks_list）
Future<List<TodoTask>> todoTasksList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoTasksList(filter: filter);

/// 获取单个任务（对应桌面 todo_tasks_get）
Future<TodoTask> todoTasksGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksGet(id: id);

/// 创建任务（对应桌面 todo_tasks_create）
Future<TodoTask> todoTasksCreate({required TodoTaskCreateInput input}) =>
    RustLib.instance.api.crateApiTodoTodoTasksCreate(input: input);

/// 更新任务（对应桌面 todo_tasks_update；patch 三态语义见模块文档，
/// 如 project_id: null 表示移出项目，而缺省键表示不改归属）
Future<TodoTask> todoTasksUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoTasksUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除任务（软删，对应桌面 todo_tasks_delete）
Future<void> todoTasksDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksDelete(id: id);

/// 更新任务排序位置（拖拽排序，对应桌面 todo_cmd::todo_tasks_update_position）
Future<void> todoTasksUpdatePosition({
  required PlatformInt64 id,
  required double position,
}) => RustLib.instance.api.crateApiTodoTodoTasksUpdatePosition(
  id: id,
  position: position,
);

/// 统一完成任务（对应桌面 todo_cmd::todo_tasks_complete；引擎下沉后三端
/// 唯一完成入口——普通任务标记完成，重复任务单事务创建下一实例（含克隆
/// 子任务）再标记本实例，移动端由此补齐「完成后推进下一实例」断层）
Future<CompleteTaskResult> todoTasksComplete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksComplete(id: id);

/// 一键复制任务（#37 小而美批次；对应桌面 todo_cmd::todo_tasks_duplicate）——
/// 克隆字段+子任务（标题+顺序），完成态/提醒/标签/评论/关联/My Day 重置，
/// position 紧邻原任务，标题「（副本）」后缀
Future<TodoTask> todoTasksDuplicate({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksDuplicate(id: id);

/// 重算任务进度（子任务变更后手动触发，对应桌面 todo_cmd::todo_tasks_recalc_percent）
Future<void> todoTasksRecalcPercent({required PlatformInt64 taskId}) =>
    RustLib.instance.api.crateApiTodoTodoTasksRecalcPercent(taskId: taskId);

/// 按 uuid 获取项目（对应桌面 todo_projects_get_by_uuid；同步引擎定位远端记录用）
Future<TodoProject?> todoProjectsGetByUuid({required String uuid}) =>
    RustLib.instance.api.crateApiTodoTodoProjectsGetByUuid(uuid: uuid);

/// 按 uuid 获取任务（对应桌面 todo_tasks_get_by_uuid）
Future<TodoTask?> todoTasksGetByUuid({required String uuid}) =>
    RustLib.instance.api.crateApiTodoTodoTasksGetByUuid(uuid: uuid);

/// 业务表记录数（对应桌面 business_count；首页仪表盘计数角标，只读聚合）
Future<PlatformInt64> businessCount({required String table}) =>
    RustLib.instance.api.crateApiTodoBusinessCount(table: table);

/// 任务详情聚合（含子任务/标签/评论/关系/提醒，对应桌面 todo_cmd::todo_tasks_get_detail）
Future<TodoTaskDetail> todoTasksGetDetail({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTasksGetDetail(id: id);

/// 列出子任务（对应桌面 todo_subtasks_list）
Future<List<TodoSubtask>> todoSubtasksList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksList(filter: filter);

/// 获取单个子任务（对应桌面 todo_subtasks_get）
Future<TodoSubtask> todoSubtasksGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksGet(id: id);

/// 创建子任务（对应桌面 todo_subtasks_create）
Future<TodoSubtask> todoSubtasksCreate({
  required TodoSubtaskCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoSubtasksCreate(input: input);

/// 更新子任务（对应桌面 todo_subtasks_update；patch 三态语义见模块文档）
Future<TodoSubtask> todoSubtasksUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoSubtasksUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除子任务（软删，对应桌面 todo_subtasks_delete）
Future<void> todoSubtasksDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksDelete(id: id);

/// 切换子任务完成状态（对应桌面 todo_cmd::todo_subtasks_toggle_done；
/// core 内部自动重算父任务 percent_done）
Future<void> todoSubtasksToggleDone({
  required PlatformInt64 subtaskId,
  required bool done,
}) => RustLib.instance.api.crateApiTodoTodoSubtasksToggleDone(
  subtaskId: subtaskId,
  done: done,
);

/// 子任务转独立任务（对应桌面 todo_cmd::todo_subtasks_promote；单事务：
/// 软删子任务行 + 承接父任务 project/priority/due 上下文建尾位新任务）
Future<TodoTask> todoSubtasksPromote({required PlatformInt64 subtaskId}) =>
    RustLib.instance.api.crateApiTodoTodoSubtasksPromote(subtaskId: subtaskId);

/// 列出标签（对应桌面 todo_labels_list）
Future<List<TodoLabel>> todoLabelsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsList(filter: filter);

/// 获取单个标签（对应桌面 todo_labels_get）
Future<TodoLabel> todoLabelsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsGet(id: id);

/// 创建标签（对应桌面 todo_labels_create）
Future<TodoLabel> todoLabelsCreate({required TodoLabelCreateInput input}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsCreate(input: input);

/// 更新标签（对应桌面 todo_labels_update；patch 三态语义见模块文档）
Future<TodoLabel> todoLabelsUpdate({
  required PlatformInt64 id,
  required String patchJson,
}) => RustLib.instance.api.crateApiTodoTodoLabelsUpdate(
  id: id,
  patchJson: patchJson,
);

/// 删除标签（软删，对应桌面 todo_labels_delete）
Future<void> todoLabelsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoLabelsDelete(id: id);

/// 列出任务↔标签关联（对应桌面 todo_task_labels_list）
Future<List<TodoTaskLabel>> todoTaskLabelsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoTaskLabelsList(filter: filter);

/// 获取单个任务↔标签关联（对应桌面 todo_task_labels_get）
Future<TodoTaskLabel> todoTaskLabelsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskLabelsGet(id: id);

/// 关联标签到任务（对应桌面 todo_task_labels_create）
Future<TodoTaskLabel> todoTaskLabelsCreate({
  required TodoTaskLabelCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoTaskLabelsCreate(input: input);

/// 解除关联（软删，对应桌面 todo_task_labels_delete）
Future<void> todoTaskLabelsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskLabelsDelete(id: id);

/// 列出评论（对应桌面 todo_comments_list）
Future<List<TodoComment>> todoCommentsList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoCommentsList(filter: filter);

/// 获取单条评论（对应桌面 todo_comments_get）
Future<TodoComment> todoCommentsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoCommentsGet(id: id);

/// 创建评论（对应桌面 todo_comments_create）
Future<TodoComment> todoCommentsCreate({
  required TodoCommentCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoCommentsCreate(input: input);

/// 删除评论（软删，对应桌面 todo_comments_delete）
Future<void> todoCommentsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoCommentsDelete(id: id);

/// 列出任务关系（对应桌面 todo_task_relations_list）
Future<List<TodoTaskRelation>> todoTaskRelationsList({
  required ListFilter filter,
}) => RustLib.instance.api.crateApiTodoTodoTaskRelationsList(filter: filter);

/// 获取单条关系（对应桌面 todo_task_relations_get）
Future<TodoTaskRelation> todoTaskRelationsGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskRelationsGet(id: id);

/// 创建任务关系（对应桌面 todo_task_relations_create）
Future<TodoTaskRelation> todoTaskRelationsCreate({
  required TodoTaskRelationCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoTaskRelationsCreate(input: input);

/// 删除任务关系（软删，对应桌面 todo_task_relations_delete）
Future<void> todoTaskRelationsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoTaskRelationsDelete(id: id);

/// 列出提醒（对应桌面 todo_reminders_list）
Future<List<TodoReminder>> todoRemindersList({required ListFilter filter}) =>
    RustLib.instance.api.crateApiTodoTodoRemindersList(filter: filter);

/// 获取单条提醒（对应桌面 todo_reminders_get）
Future<TodoReminder> todoRemindersGet({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoRemindersGet(id: id);

/// 创建提醒（对应桌面 todo_reminders_create）
Future<TodoReminder> todoRemindersCreate({
  required TodoReminderCreateInput input,
}) => RustLib.instance.api.crateApiTodoTodoRemindersCreate(input: input);

/// 删除提醒（软删，对应桌面 todo_reminders_delete）
Future<void> todoRemindersDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTodoTodoRemindersDelete(id: id);

/// 任务→标签投影（对应桌面 task_labels_projection；一次往返替代两次整表）
Future<List<TaskLabelsProjection>> taskLabelsProjection() =>
    RustLib.instance.api.crateApiTodoTaskLabelsProjection();

/// 任务→提醒投影（对应桌面 task_reminders_projection；组内 remind_at 升序）
Future<List<TaskRemindersProjection>> taskRemindersProjection() =>
    RustLib.instance.api.crateApiTodoTaskRemindersProjection();

/// 任务→关联计数旗标（对应桌面 task_dependency_flags；Wave 5 的 C7 消费）
Future<List<TaskDependencyFlags>> taskDependencyFlags() =>
    RustLib.instance.api.crateApiTodoTaskDependencyFlags();

/// 任务→「有描述」投影（对应桌面 task_description_flags；只出有描述的行）
Future<List<TaskDescriptionFlag>> taskDescriptionFlags() =>
    RustLib.instance.api.crateApiTodoTaskDescriptionFlags();
