// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pool`, `tick_once`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// 启动回收站 TTL 清理守护（幂等；Dart 在 DB 就绪后调用一次，BootGate 接线）
///
/// 每日最多实际清理一次；应用多日未开时下次启动首轮 tick 即补清。
Future<void> startTrashScheduler() =>
    RustLib.instance.api.crateApiTrashStartTrashScheduler();

/// 回收站任务列表（最近删除排最前；对应桌面 trash_tasks_list）
Future<List<TodoTask>> trashTasksList() =>
    RustLib.instance.api.crateApiTrashTrashTasksList();

/// 恢复任务（原项目已删则落未分组；对应桌面 trash_task_restore）
Future<TodoTask> trashTaskRestore({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTrashTrashTaskRestore(id: id);

/// 彻底删除单个回收站任务（对应桌面 trash_task_purge）
Future<void> trashTaskPurge({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiTrashTrashTaskPurge(id: id);

/// 清空回收站，返回删除数（对应桌面 trash_purge_all）
Future<BigInt> trashPurgeAll() =>
    RustLib.instance.api.crateApiTrashTrashPurgeAll();

/// TTL 过期清理一次（对应桌面 trash_purge_expired；通常由守护触发）
Future<TrashPurgeStats> trashPurgeExpired() =>
    RustLib.instance.api.crateApiTrashTrashPurgeExpired();

/// 回收站元数据（对应桌面 trash_meta）
Future<TrashMeta> trashMeta() => RustLib.instance.api.crateApiTrashTrashMeta();

/// 设置保留天数（档位 7/30/90/0=永久；对应桌面 trash_set_retention_days）
Future<void> trashSetRetentionDays({required PlatformInt64 days}) =>
    RustLib.instance.api.crateApiTrashTrashSetRetentionDays(days: days);

/// 回收站元数据（镜像 core trash_api::TrashMeta）
class TrashMeta {
  /// 保留天数（0 = 永久；默认 30，档位 7/30/90/0）
  final PlatformInt64 retentionDays;

  /// 上次 TTL 自动清理时间（ms；0 = 从未执行）
  final PlatformInt64 lastPurgeMs;

  const TrashMeta({required this.retentionDays, required this.lastPurgeMs});

  @override
  int get hashCode => retentionDays.hashCode ^ lastPurgeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrashMeta &&
          runtimeType == other.runtimeType &&
          retentionDays == other.retentionDays &&
          lastPurgeMs == other.lastPurgeMs;
}

/// TTL 清理统计（镜像 core trash_api::PurgeStats）
class TrashPurgeStats {
  final BigInt purged;
  final BigInt guarded;
  final bool ran;

  const TrashPurgeStats({
    required this.purged,
    required this.guarded,
    required this.ran,
  });

  @override
  int get hashCode => purged.hashCode ^ guarded.hashCode ^ ran.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrashPurgeStats &&
          runtimeType == other.runtimeType &&
          purged == other.purged &&
          guarded == other.guarded &&
          ran == other.ran;
}
