// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 拉小组件快照：今天截止或已逾期的未完成任务（优先级降序，limit 截断）
Future<List<WidgetTodoItem>> widgetTodoQuery({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiWidgetWidgetTodoQuery(limit: limit);

/// 小组件勾选切换（done=1 完成 / 0 取消；完成复用 complete 全语义）
Future<void> widgetTodoToggle({required PlatformInt64 id, required int done}) =>
    RustLib.instance.api.crateApiWidgetWidgetTodoToggle(id: id, done: done);

/// 小组件任务行（FRB 镜像；RemoteViews 渲染最小字段集）
class WidgetTodoItem {
  final PlatformInt64 id;
  final String uuid;
  final String title;
  final int priority;
  final int done;

  const WidgetTodoItem({
    required this.id,
    required this.uuid,
    required this.title,
    required this.priority,
    required this.done,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      title.hashCode ^
      priority.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WidgetTodoItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          title == other.title &&
          priority == other.priority &&
          done == other.done;
}
